### ISSUE TITLE
jsperf.com website down?

### ISSUE THREAD

**Issue by girishkvs** [jsperf/jsperf.com#101]
Hello,

I see that jsperf.com website is down and it says that it will be unavailable until the release of v2. Can I know when will it be available?
Btw I am trying to access a benchmark result http://jsperf.com/indexeddb-vs-localstorage which was not done by me and I didn't fork that.

Thanks,
Girish

**Comment by madskonradsen** [comment]
By looking at the milestone for v2, you can track the progress. If you are in dire need of jsperf, then consider making a PR. https://github.com/jsperf/jsperf.com/milestones/v2
This is an open source project. So no fixed deadline,
