### ISSUE TITLE
I understand the reason behind #18, but can we, almost 1 year later, at least get a read-only version?

### ISSUE THREAD

**Issue by jlsjonas** [jsperf/jsperf.com#110]
Hi,

I completely understand why things happened, however; since the issue seems to be mainly related to posting, wouldn't it be possible to put up a read-only version of the previous site? I'm getting so many broken links with useful/important information.

Best regards
Jonas

**Comment by mathiasbynens** [comment]
Please help out: https://github.com/jsperf/jsperf.com/milestones/v2

**Comment by JoshuaKGoldberg** [comment]
@mathiasbynens I'm a little confused. Is v2 required for a read-only version? Is there a page with more context?
