### ISSUE TITLE
FEATURE Memory/Heap Graphs using performance.memory

### ISSUE THREAD

**Issue by roblav96** [jsperf/jsperf.com#111]
In my Cordova app I've built an embedded memory usage monitor. I think something like this would be incredibly useful for jsperf.

![stats](http://s32.postimg.org/fo9r68vzp/Screenshot_20160522_034123.png)

**Comment by roblav96** [comment]
Thoughts?

**Comment by madskonradsen** [comment]
Wouldn't such thing be visible through the dashboard of Digital Ocean etc.? In that case, it wouldn't be that useful compared to the overhead of writing and maintaining it?

**Comment by jdalton** [comment]
I think it's better to memory profile real apps rather than synthetic tight-loop benchmarks.
