### ISSUE TITLE
Not allowed to create a test on the dev instance

### ISSUE THREAD

**Issue by Haroenv** [jsperf/jsperf.com#112]
`Protocol "https:" not supported. Expected "http:".`

This message keeps appearing, even after I have changed the url to `http:`

**Comment by maxbeatty** [comment]
where are you seeing this? can you provide a URL?

**Comment by Haroenv** [comment]
https://jsperf-dev.herokuapp.com/ when making a new test

**Comment by maxbeatty** [comment]
Sorry for the confusion. That app is not maintained anymore so I've deleted it. If there's a link to it somewhere, please open a PR to remove it 😸

**Comment by Haroenv** [comment]
Okay, in that case, is there a working version online somewhere?
