### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#12]
- [x] [create](https://github.com/maxbeatty/jsperf.com/blob/breakdown/_tpl/comments.tpl)
- [ ] [edit](https://github.com/maxbeatty/jsperf.com/blob/breakdown/_tpl/editComment.tpl)
- [x] [delete](https://github.com/maxbeatty/jsperf.com/blob/breakdown/_tpl/deleteComment.tpl)

**Comment by mathiasbynens** [comment]
Adding the admin label since `edit` and `delete` are admin features. Posting comments is not a hard requirement for v2, so assigning to v2.1.

**Comment by maxbeatty** [comment]
Is editing still a valid feature? If a comment is malicious or offensive, why not just delete?

**Comment by mathiasbynens** [comment]
Editing allowed you to edit your own comments (to correct typos etc.).

**Comment by mathiasbynens** [comment]
I should have clarified that before, i.e. _global_ comment `edit`/`delete` are admin features, but everyone can edit/delete their own comments.
