### ISSUE TITLE
Clearer instructions for getting a working dev environment.

### ISSUE THREAD

**Issue by madskonradsen** [jsperf/jsperf.com#126]
I've spent a good amount of time on getting a connection to the database. Either the instructions could be clearer or something might be misconfigured in the setup.

"MYSQL_PASSWORD=$MYSQL_PASSWORD docker-compose up" and "npm start" should _not_ be running at the same time, right?

Running the docker-compose up command yields the following
![esixwa](https://cloud.githubusercontent.com/assets/1265787/16733146/95994f40-4780-11e6-91af-34c4f92ca3e6.png)
and it seems like it cannot access the web-docker-container.

The .env contains the following:
```
NODE_ENV=development
SCHEME=http
DOMAIN=localhost
PORT=3000
...
```

**Comment by DevSide** [comment]
The PR #116 fix this issue. You don't need docker to run in dev mode.

**Comment by maxbeatty** [comment]
> "MYSQL_PASSWORD=$MYSQL_PASSWORD docker-compose up" and "npm start" should not be running at the same time, right?

In most cases, yes either use Docker Compose to run all of the containers orchestrated together or you can run MySQL and Node.js independently (`npm start`).

**Comment by madskonradsen** [comment]
Isn't it strange that `host: 'db',` is hardcoded in db.js then? In most cases it would localhost?

![image](https://cloud.githubusercontent.com/assets/1265787/16737505/f186d33e-4791-11e6-993d-da7604e82fe9.png)

**Comment by maxbeatty** [comment]
> Isn't it strange that host: 'db', is hardcoded in db.js then? In most cases it would localhost?

It's possible not to use Docker but there's a strong preference (such as hardcoded host names) for it since that's how we're currently running this in "production." [Trying to keep dev/prod parity small](http://12factor.net/dev-prod-parity) 

Documentation can always be better. If there are ways to make the README clearer without changing the current configuration, please open a PR 😄 (Don't want to change current configuration because we're nearing launch and feel pretty confident in it at this point)

**Comment by madskonradsen** [comment]
I see, it makes sense! :) I will open a PR later, and probably create a small script that makes stuff a bit easier when not using docker :)

**Comment by sandy-adi** [comment]
@maxbeatty I'm trying to run jsperf on docker: I'm getting the following error:

```
Building lb
Step 1 : FROM gliderlabs/alpine:3.4
 ---> eeae34df12d9
Step 2 : RUN echo "@testing http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
 ---> Using cache
 ---> 120ddc1b250d
Step 3 : RUN apk-install nginx curl runit@testing
 ---> Running in b6f814026241
fetch http://alpine.gliderlabs.com/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  runit (missing):
    required by: world[runit]
ERROR: Service 'lb' failed to build: The command '/bin/sh -c apk-install nginx curl runit@testing' returned a non-zero code: 1
```
Any idea what I could be missing. I'm running docker natively on MAC

**Comment by maxbeatty** [comment]
> apk-install nginx curl runit@testing

That could be a networking issue on your end or a registry problem with alpine or a number of other things beyond the scope of this issue and repo

**Comment by sandy-adi** [comment]
@maxbeatty it appears like the `@testing` package repository no longer works. I was able to get around this issue by making the following changes

```
RUN echo "@community http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk-install runit@community
```

**Comment by mamboer** [comment]
@sandy-adi thanks so much for the trick
