### ISSUE TITLE
Missing headTitle in test/index.js

### ISSUE THREAD

**Issue by madskonradsen** [jsperf/jsperf.com#127]
... which causes jsperf to fallback to the generic `<title>`

The headTitle should be set to the same as the test-title(and should not mention the revision, if we are stricly trying to mimic jsPerf v1)

**Comment by maxbeatty** [comment]
Fixed by https://github.com/jsperf/jsperf.com/commit/42a0f8c07f0112535946cb90994489d11520c67b
