### ISSUE TITLE
Consider adding description of new database to 404-page

### ISSUE THREAD

**Issue by madskonradsen** [jsperf/jsperf.com#128]
I assume that the old database of jsPerf is history which means that a lot of links on stackoverflow will be invalid. Consider adding a description to the 404 page that says something along the lines of that the DB have been reset.

**Comment by mathiasbynens** [comment]
No, the old database is imported. Old tests are still there. As soon as v2 goes live, those URLs will start to return 200s again!

**Comment by madskonradsen** [comment]
Oh, my bad! Sorry! Isn't it super bloated by all the spammers? :P

**Comment by mathiasbynens** [comment]
Yeah, I’ve removed *some* of the spam before importing the dump but not all of it. Getting rid of more spam would be a nice v3 project ;)

**Comment by madskonradsen** [comment]
Haha! Regex would probably get us a long way ;)
