### ISSUE TITLE
Unusable to most developers because of nvm

### ISSUE THREAD

**Issue by StoneCypher** [jsperf/jsperf.com#132]
Can you help me understand why you're requiring a specific node version, which locks Windows users (and therefore ~90% of js devs, or ~35% of js devs on github) out of using this because of `nvm`, one of the reddest flag of all red flag node dependencies?

Your site is also gone, so I have no other options

**Comment by mathiasbynens** [comment]
How would you not require a specific Node version and still have everything work? You’re free to try running the code on other Node versions but you can’t reasonably expect us to support every possible version out there.

**Comment by StoneCypher** [comment]
You realize that almost no node project requires `nvm`, and that it's really *really* weird for you to suggest that pinning node is normal, right?

**Comment by StoneCypher** [comment]
It would probably be good enough for you to just support current node, like everyone else does

**Comment by StoneCypher** [comment]
It would probably be good enough for you to just support current node, like everyone else does

is there an older version of this project that doesn't pin node?  i don't need a full spread of browsers.  the only reason i'm here at all is that someone's giving extremely bad advice in public, and refuses to fix it until i give them benchmarks of the sensible code i gave them

but the site is down and i can't run local, and they refuse to update their benchmarks with the code they were given

there's people switching away from vanilla to libraries because they have been given bad information about performance, and the person giving the bad advice is requiring me to redo their work in your tool or else they'll keep teaching the novices the incorrect thing

i'm just trying to help some newbies

i don't need deep results.  i wrote my own benchmark rig but he refuses to believe the results, even though the part that cover his own benchmark results seem to agree.

can you help me help these kids?

**Comment by mathiasbynens** [comment]
The old PHP version is here: https://github.com/mathiasbynens/jsperf.com

I can’t say I understand your setup at all, though. Are you saying you’re able to run Docker etc. successfully and the only thing failing is `nvm` _within the container_? That sounds… weird.

**Comment by StoneCypher** [comment]
No.  I didn't bother with Docker.

I tried to follow the instructions in the readme on NPM, which say clone the repo, set the NVM version, and run NPM install.

When I noticed the dockerfile, I also noticed a ticket that said "you don't need docker in dev mode."

So I didn't think I needed docker, because the instructions don't nominate it at all.
