### ISSUE TITLE
Consider adding caching

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#136]
[hapijs/catbox](https://github.com/hapijs/catbox) would be a good fit with our setup with possibly [redis](https://github.com/hapijs/catbox-redis) as the store

🎩 @asilluron

**Comment by STRML** [comment]
If you're willing to commit to Redis, we maintain & use [redis-memoizer](https://github.com/BitMEX/redis-memoizer), which is about as simple to use as it gets. It's not super-smart but it makes it easy to memoize expensive async operations.

**Comment by madskonradsen** [comment]
redis-memoizer sounds pretty cool, and it would probably only be necessary to add caching to the getTestPage-method in test/index.js
