### ISSUE TITLE
Upgrade marked

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#146]
- [Vulnerability](https://snyk.io/vuln/npm:marked:20150520)
- [Fix awaiting release](https://github.com/chjj/marked/pull/592)
- [Alternative module](https://github.com/jonschlinkert/remarkable)

**Comment by mathiasbynens** [comment]
Note that for jsPerf, this is less of an issue since it’s easy enough to XSS jsPerf anyway — running user-supplied JS is kind of its whole purpose.
