### ISSUE TITLE
Add ability to edit test page

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#15]
https://github.com/maxbeatty/jsperf.com/blob/breakdown/_tpl/edit.tpl

**Comment by rwthompsonii** [comment]
The intent here is to translate this to JS yes?  I'm just poking around the project and looking if there's anything that I could work on. 

Thanks.

**Comment by mathiasbynens** [comment]
@rwthompsonii Yeah.

**Comment by DevSide** [comment]
Do you still allow anonymous user to edit tests ?

**Comment by mathiasbynens** [comment]
> Do you still allow anonymous user to edit tests ?

They need to be logged in through GitHub authentication.
