### ISSUE TITLE
JavaScript error as a result of spam-question being removed

### ISSUE THREAD

**Issue by madskonradsen** [jsperf/jsperf.com#152]
Uncaught TypeError: Cannot set property 'value' of null.

message: Uncaught TypeError: Cannot set property 'value' of null
fileName: http://localhost:3000/test.js
lineNumber: 20580

![skaermbillede 2016-08-17 kl 17 37 54](https://cloud.githubusercontent.com/assets/1265787/17742697/58d66618-64a1-11e6-8a93-4032013ffc24.png)

**Comment by madskonradsen** [comment]
Should probably be added to milestone v2

**Comment by maxbeatty** [comment]
Can you make sure you are up to date with dependencies? That line was removed [here](https://github.com/bestiejs/benchmark.js/pull/151/files#diff-81cd1eec109c1a627eeb236617e5cc97L230) (and that file is gulped [here](https://github.com/jsperf/benchmark.js-wrapper/blob/152abb17f560b797bcb96caa6cca5a8cbb7885ce/gulpfile.js#L24) for the module we request [here](https://github.com/jsperf/jsperf.com/blob/c9c666e2e01f93afa7fc2544b2902f785941a7f4/package.json#L30))

**Comment by madskonradsen** [comment]
Just tried hitting the download-button on this repo and downloading the master-branch as a zip, running npm install and it's still there :-/

**Comment by maxbeatty** [comment]
once jsperf/benchmark.js-wrapper#3 is merged, tagged, and published to npm will need to update dependency here

**Comment by mathiasbynens** [comment]
Done: https://github.com/jsperf/benchmark.js-wrapper/releases/tag/v1.0.3

@madskonradsen Wanna submit the patch to update the dependency here?

**Comment by madskonradsen** [comment]
Sure, updated in #155
