### ISSUE TITLE
jsPerf is temporarily unavailable while we’re working on releasing v2. Please try again later.

### ISSUE THREAD

**Issue by blackmambahk** [jsperf/jsperf.com#169]
Haven't been able to access  jsperf for a very long time now. 

Is it totally dead ? 

or is someone working on something to restore access, used to be a very useful tool

**Comment by mathiasbynens** [comment]
> or is someone working on something to restore access

See this repository.

**Comment by heavensrevenge** [comment]
Can't wait to see v2 up and running once you and @maxbeatty are satisfied with the result.  It will truly be a day for celebration!
