### ISSUE TITLE
Error on jsperf-dev on Heroku

### ISSUE THREAD

**Issue by d10** [jsperf/jsperf.com#17]
The dev page errors with:
```
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```

**Comment by maxbeatty** [comment]
Fixed up the config and was able to successfully add a test

**Comment by jdalton** [comment]
Currently the dev server is complaining about:
```js
Protocol "https:" not supported. Expected "http:".
```
when trying to save a test case.

**Comment by mathiasbynens** [comment]
@jdalton Which dev server are you trying? We’re no longer using Heroku.

**Comment by jdalton** [comment]
> We’re no longer using Heroku.

That's the one. No worries.
