### ISSUE TITLE
ER_NO_DEFAULT_FOR_FIELD: Field 'hits' doesn't have a default value

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#178]
When adding a test case, error appears at top of page. Nothing user can do. I believe this is an issue with the database instance and [not the schema we have in source control](https://github.com/jsperf/jsperf.com/blob/d98a66e8d590d23bf820678a9479aa09e9be05c4/setup/sql/create_pages.sql#L15)

**Comment by BurtHarris** [comment]
I saw this too, but on the jsper**v** web site.   See #191

**Comment by mathiasbynens** [comment]
This is about the `hits` field in the `pages` table. The default value should be `0`.

**Comment by mathiasbynens** [comment]
Just ran this on the server:

```
mysql> ALTER TABLE pages MODIFY COLUMN hits bigint(20) NOT NULL DEFAULT '0';
Query OK, 0 rows affected (0.08 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

That should fix it.
