### ISSUE TITLE
Require login before posting test cases / comments

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#19]
Ref. #18. Preferably [GitHub OAuth](https://developer.github.com/v3/oauth/).

**Comment by Shnoulle** [comment]
Include other OAuth can be a good idea too .... http://doc.gitlab.com/ce/integration/oauth_provider.html

**Comment by jeremykohn** [comment]
How about logging in with StackExchange? That would make it easy for  StackOverflow users to create jsPerf tests and post links to them.

https://api.stackexchange.com/docs/authentication

**Comment by ro-savage** [comment]
If the idea is to stop JSPref filling with spam (https://github.com/jsperf/jsperf.com/issues/18#issuecomment-113569132), why have a login system at all? 

Why not a captcha for non-logged in users and nothing for logged in users.

Plenty of us like to modify tests we've found and logging in is just an added annoyance and keeps new users away.

**Comment by Burstaholic** [comment]
Given the link in #18, this should probably be added to the `v2` milestone.

**Comment by Lor-Saba** [comment]
Don't know if this is a good or dumb idea but ..you could identify a submission based on whether the user is anonymous / registered or pro (registered+ ? donators)..:

by an anonymous user: if the submission isn't visited after 24h it will be removed (reset when visited),
by a registered user:  //same//  ~6months  //same//
by a registered+ user: stored for life, wont be removed.

This wont stop the spam but maybe could help for storage (and could help you to maintain this amazing site).

**Comment by oriadam** [comment]
+1 for SE/github auth login.
Anonymous user editing is nice to have, but not mandatory.
