### ISSUE TITLE
Preparation code output displays JS source

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#228]
The “preparation code output” section should show the `initHTML` with any `script` tags and their contents stripped out.

Currently, it removes `<script>` and `</script>`, but leaves the contents intact.

https://github.com/jsperf/jsperf.com/blob/04233d64da81db617586d28b2c2e5c5758411a81/server/web/test/index.hbs#L61-L69

Example test case where this makes the output look confusing: https://jsperf.com/tooooooooooofixed

**Comment by demoneaux** [comment]
I think this can be closed with #231. The [current regex](https://github.com/jsperf/jsperf.com/blob/ed21babe33688b90c2df16706c5c8efb13190d6e/server/lib/regex.js#L88) does appear to strip the contents of `<script>`s.

**Comment by mathiasbynens** [comment]
@demoneaux Correct! The same bad test striketh again :(
