### ISSUE TITLE
Hosting recommendations?

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#23]
Any recommendations for decent io.js + MySQL hosting?

Heroku? DigitalOcean? Any other recommendations?

Quoting <https://github.com/h5bp/lazyweb-requests/issues/174#issuecomment-74782606>:

> Guessing the free tier of Heroku won’t cut it. [Hosting compatible with Node](https://github.com/joyent/node/wiki/node-hosting) Could anyone donate hosting?

About hosting costs: I’ll continue to pay for it out of my own pocket. Hopefully in the future user donations could (help) pay for the hosting. Or perhaps a hosting company would be willing to donate a box for jsPerf?

**Comment by realityking** [comment]
No promises, but how big of a setup does jsperf need?

**Comment by nhz-io** [comment]
Ok, i've been sending mails all around and stuff started to move. Here is what i got from stackexchange:

---

 David Haney

Jun 24, 15:04

This is really interesting. If they (JSPerf) can map a URL to a JS/HTML/CSS code output, one thing we could do is provide a list of URLs, get back a set of code, and run an update/rebake to insert snippets for each link. That might work. Thoughts?

-Haney

---

Admin

Jun 24, 13:02

**Free text follows:**

Hey there, this mail is on behalf of jsperf.com.
As you may have noticed the site is down (overload of spam),
and we are trying to come up with the solution to this problem.
See here: https://github.com/jsperf/jsperf.com/issues/18

If you are interested in offering any kind of help, like hosting the resource please dont hesistate.

---

**Comment by ZombieHippie** [comment]
I ended up using vps.me, but I can't argue that they are better than any other one hosting company.

**Comment by arjunmehta** [comment]
Consider Linode, they are very diligent in upgrading their systems, and making sure that you get what you're paying for. You can scale easily. You'd have to set everything up from scratch though.

**Comment by steelbrain** [comment]
Try vultr.com they are both faster and cheaper than the competetion.

**Comment by haneefmubarak** [comment]
I do know that Linode is extremely flexible and gives solid performance at quite reasonable rates.

That said, you might look into https://www.bluehost.com/opensource, because last year at a conference I believe I remember a Bluehost rep saying that they are willing to provide some hosting services for open source projects.

**Comment by gtomitsuka** [comment]
[Amazon EC2](http://aws.amazon.com/ec2/) would work, too. It's easy to scale, and the price is similar to DigitalOcean.

**Comment by haneefmubarak** [comment]
The problem with EC2 is a horrible lack of reliability (stuff fails all the
time), consistent performance (packet loss is considered normal), and
availability (loads and loads of machines have simultaneously failed
before).

DigitalOcean and Linode both have solid performance, reliability, and
availability. The only other reasonably priced cloud that I've seen with a
better level of performance, reliability, and availability is Google Cloud
Platform.

**Comment by STRML** [comment]
If you want a really beefy single machine, Hetzner offers some great bare-metal servers [at auction](https://robot.your-server.de/order/market/country/US). 

Otherwise if you're load-balancing, you can't really beat the pricing and reliability at DigitalOcean. I believe that in #18 they offered to help out anyway. You could run a simple nginx or haproxy LB back to a bunch of iojs instances. At the proxy layer you could configure a lot more abuse / DDoS protection.

I'm a big fan of JSPerf and used to use it constantly. Please feel free to [contact me](mailto:sam@bitmex.com) if you'd like some help getting it back online.

**Comment by entr0cks** [comment]
I've been using [Vultr](http://www.vultr.com/?ref=6809751)(link with a reference) and they're quite good - at the same price range better performance and they don't oversell their services.
Certainly deserves a look into :)

**Comment by tripflex** [comment]
Stay away from BlueHost, really anybody with EIG you will regret it later, I promise.

With that said, I <3 open source, and would be more than happy to give you a box to run everything on for free.  Get in touch and we can get this all setup for you ASAP

**Comment by STRML** [comment]
+1 stay away from anything EIG. Also happy to offer capacity.

**Comment by mathiasbynens** [comment]
@rauchg from @zeit offered to host jsPerf for free: https://twitter.com/rauchg/status/749048067165294592 ♥

One thing that’s unclear to me at this point though is how we’d handle the MySQL database. We’d still need a separate host for that, right?

**Comment by madskonradsen** [comment]
Would zeit even be able to handle the docker-setup? Looks like a pure NodeJS host?

**Comment by STRML** [comment]
Could do some bare-metal containers on Joyent. I have a budget on there I'd be willing to spend, and I could ask if they'd be willing to sponsor. Given how popular jsperf is & how inexpensive it would be to host, feels like a no-brainer.

**Comment by madskonradsen** [comment]
As far as i remembers DigitalOcean talked about donating hosting in another thread? https://developers.digitalocean.com/opensource/ 

"Whether it's sponsoring MeetUps or hosting, we're always looking for ways to help open source projects. Reach out to us at opensource@digitalocean.com, and let's figure out how we can work together." 

They would at least be able to run the docker-setup as they have VPS'.

**Comment by maxbeatty** [comment]
We are currently using Digital Ocean to continuously deliver [this repo's Docker image](https://hub.docker.com/r/jsperf/jsperf.com/) and run [the other containers](https://github.com/jsperf/jsperf.com/blob/f9f05fbccd178926c9ae7956a284799ef896b508/docker-compose.yml).

Using ZEIT Now would let us put load balancing and scale on them, but would require some non-trivial configuration and deployment changes. We'd still need our Digital Ocean Droplet for MySQL.

**Comment by mateothegreat** [comment]
We can get you off of mysql and onto a nosql db like mongo.
Now that you've got a lot of stuff re-arranged I can drop in a new design pattern.

The mysql schemas need to be redesigned.. we have nested sub queries performing sorting on aggregation functions while locking tables and blocking other reads/select's.

@mathiasbynens Do you have a snapshot of your production mysql database(s) that I can snap and get some metrics off of to see what the footprint is? or can you pull the stats out for me?

**Comment by mathiasbynens** [comment]
I can send you a dump. Send me an email: mathias@qiwi.be
