### ISSUE TITLE
Markdown in titles for individual test snippets not converted correctly

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#237]
E.g. https://jsperf.com/slugs#runner

The second test snippet has the title:

```
Using `.match()` and `.join()`
```

This is rendered as:

```html
Using <code>.match()</code> and `.join()`
```

It should be:

```html
Using <code>.match()</code> and <code>.join()</code>
```

**Comment by maxbeatty** [comment]
Should all Markdown be supported in titles? If so [`addCode`](https://github.com/jsperf/jsperf.com/blob/d29ce16511950e259ba4e4bee64519f1700ab220/templates/helpers/addCode.js) can be switched out for [`markdown`](https://github.com/jsperf/jsperf.com/blob/d29ce16511950e259ba4e4bee64519f1700ab220/templates/helpers/markdown.js) in [the template](https://github.com/jsperf/jsperf.com/blob/d29ce16511950e259ba4e4bee64519f1700ab220/server/web/test/index.hbs#L90).

If we just want to support multiple `code`, then [`addCode` regex](https://github.com/jsperf/jsperf.com/blob/d29ce16511950e259ba4e4bee64519f1700ab220/templates/helpers/addCode.js#L4) needs to be fixed.

**Comment by mathiasbynens** [comment]
Good point — we probably just want to support multiple `code` spans in one title, like the old site used to do.
