### ISSUE TITLE
Cannot log in with Github when running docker-compose up

### ISSUE THREAD

**Issue by OrKoN** [jsperf/jsperf.com#240]
Hi,

I have the following .dotenv:

```
NODE_ENV=development
SCHEME=http
DOMAIN=dev.jsperf.com
PORT=3000
ADMIN_EMAIL=xxxx@gmail.com
BROWSERSCOPE=xxxx
BELL_COOKIE_PASS=xxxx
COOKIE_PASS=xxx
GITHUB_CLIENT_ID=xxxx
GITHUB_CLIENT_SECRET=xxxx
MYSQL_PASSWORD=xxx
```

and I run docker-compose up. So on port 80 runs the load balancer (port is exposed), node server runs on port 3000 (not exposed). When I try to sign in I get redirected to Github with redirect_url = 'http://dev.jsperf.com:3000...' instead of just 'http://dev.jsperf.com...' or 'http://dev.jsperf.com:80...'. So when Github redirects me back to port 3000 there is nothing running there.

I had to tweak strategies.js and define `http://dev.jsperf.com` as the location in order to make it work.

How do you solve this?

**Comment by maxbeatty** [comment]
[the GitHub OAuth location](https://github.com/jsperf/jsperf.com/blob/d29ce16511950e259ba4e4bee64519f1700ab220/server/web/auth/strategies.js#L17) is determined by [the manifest](https://github.com/jsperf/jsperf.com/blob/d29ce16511950e259ba4e4bee64519f1700ab220/manifest.js#L103) which comes from [the config](https://github.com/jsperf/jsperf.com/blob/d29ce16511950e259ba4e4bee64519f1700ab220/config.js#L7) where we [normalize the domain to include port in some cases](https://github.com/jsperf/jsperf.com/blob/d29ce16511950e259ba4e4bee64519f1700ab220/lib/config.js#L25). this is a consequence of catering to both Docker and non-Docker setups. I believe to get around this you can just change your `.env` to use 80 and [Docker Compose will keep using 3000 for the things it needs](https://github.com/jsperf/jsperf.com/blob/d29ce16511950e259ba4e4bee64519f1700ab220/docker-compose.yml#L8-L11)

**Comment by OrKoN** [comment]
Changing port in .env does not help. I think docker-compose.yam overrides .env https://github.com/jsperf/jsperf.com/blob/master/docker-compose.yml#L11

**Comment by asilluron** [comment]
You need to follow the developer instructions to the letter:

"Register a new OAuth GitHub development application by going to your settings page in github. Take note to copy the "Client ID" and "Client Secret". The callback URL is simply the root url of the application, e.g., http://localhost:3000"

Unless you actually have access to dev.jsperf.com or setup your local dns resolution to mock this (e.g., editing your host file), you will likely be using  http://localhost:3000.

**Comment by OrKoN** [comment]
yes, I have local dns, and no, port 3000 is not mapped by the docker compose. Load balance runs on port 80 and this is the entry point for the site. But the node server generates a redirect url with port 3000 which is an internal port of node server.

**Comment by asilluron** [comment]
Oh, I see. Okay, just change the port in your .env to 80. 

This does not affect the internal exposed port, it's just used to create the callback url.

**Comment by OrKoN** [comment]
@asilluron this does not work. I have changed it to 80 in .env and rebuilt. But it still puts 3000 in the redirect URL. Probably docker-compose.yaml overrides .env https://github.com/jsperf/jsperf.com/blob/master/docker-compose.yml#L11 so it does not matter what port you have in .env when using docker compose.

**Comment by asilluron** [comment]
It does but it's ignored by manifest:
 
https://github.com/jsperf/jsperf.com/blob/master/manifest.js#L103

We simply depend on the domain + scheme for the callback url

**Comment by OrKoN** [comment]
If you console.log `options.oauth.location` in web/auth/strategies, you will see that it has the port:

![selection_066](https://cloud.githubusercontent.com/assets/399150/19674018/3c1029a0-9a85-11e6-9d73-4a9cf0b54d0a.png)

**Comment by maxbeatty** [comment]
#253 solves this by explicitly declaring the oauth callback
