### ISSUE TITLE
Website redesign

### ISSUE THREAD

**Issue by veksen** [jsperf/jsperf.com#242]
Hello! I am wondering if you are interested by a redesign of JSPerf? I'd like to check-in before putting time and effort into proposing a design and creating PRs.

I've recently put some energy on the Lodash website redesign, and JSPerf being my second most favorite JS resource, I'd like to give it some love as well!

**Comment by mathiasbynens** [comment]
Hey @veksen!

We’re still working on porting the functionality from the old website to the new version. As such, _a complete make-over_ is not a priority right now.

I think the best way forward is to send PRs that implement small, incremental UI/UX changes, one at a time. What do you think?

**Comment by veksen** [comment]
Works for me! I'll get started soonish.

**Comment by asilluron** [comment]
Closing the issue so we can track by individual improvements instead.

**Comment by veksen** [comment]
My first proposal is something like this. If that works, I'll start implementing it in small PRs.

![jsperf](https://cloud.githubusercontent.com/assets/3461986/20870330/3a4d6e72-ba54-11e6-8aa6-16db005c1229.png)

**Comment by mathiasbynens** [comment]
@veksen That looks great! I’m personally not the biggest fan of the Trebuchet MS font but that’s a small detail that can easily be changed after some experimentation, right? As far as I’m concerned, let’s get those small & incremental PRs going ;) 👍

**Comment by veksen** [comment]
The body/header fonts is PT Sans, the monospace font is Source Sans Pro, and the logo is Familiar Pro

**Comment by veksen** [comment]
What about the logo? I tried going for something a little more actual and less boring.

The buttons were a last minute change. The used to be flat, without rounded corners. The gradient inside is a bit particular, it's angled at 113 degrees (and not 135), and it's a little hard to balance across different button sizes... We'll see. Also wasn't completely sure about the table, I'm not sure if it looks too bold (especially compared to the old one that was very table looking).

**Comment by madskonradsen** [comment]
Wow, didn't see the proposal you made as the ticket got closed... It looks super neat @veksen! (and I really think the new logo looks good)
