### ISSUE TITLE
Beautify code break arrow functions 

### ISSUE THREAD

**Issue by Ginden** [jsperf/jsperf.com#248]
Minimal test case:
1. Enter `(a => a)`
2. Press _Beautify code_.

Expected result:
`(a => a)`

Actual result:

`(a = > a)`

**Comment by mathiasbynens** [comment]
Looks like this would be fixed by updating our copy of https://github.com/beautify-web/js-beautify. Patches welcome!

**Comment by maxbeatty** [comment]
Tempted to remove "beautify" functionality

**Comment by mathiasbynens** [comment]
Yeah, let’s get rid of it. 👍 People who want this functionality can use a userscript / browser extension.
