### ISSUE TITLE
“Unexpected response from browserscope.org” shouldn’t prevent new test creation

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#257]
Whenever the “Unexpected response from browserscope.org” occurs, jsPerf should still create the test, just without a Browserscope ID.

When the test page is accessed we can re-attempt to get a Browserscope ID for this test.

**Comment by boozedog** [comment]
+1 getting this error today

**Comment by OliverJAsh** [comment]
Also getting this error today

**Comment by mathiasbynens** [comment]
@maxbeatty’s fix is now live. @boozedog @OliverJAsh Everything ok now?

**Comment by OliverJAsh** [comment]
Great, thanks. I can now create a test, but can't edit it. When I try to
make a simple change I see "Not all tests inserted"

**Comment by boozedog** [comment]
I'm seeing same as @OliverJAsh ... "Not all tests inserted"
