### ISSUE TITLE
Can't edit tests.

### ISSUE THREAD

**Issue by Pecacheu** [jsperf/jsperf.com#258]
I can't edit any tests at all, regardless of whether they're public or private, mine or other people's.

It either gives the error `Not all tests inserted` or `Please review required fields and save again.`, or sometimes an infinite loop of Captchas. There also isn't an add code-snippet button as described in #247.

Tried Chrome and Edge on Windows 10, and Chrome on Mac OS X.

**Comment by cuixiping** [comment]
I met the same issue.

**Comment by vegeta897** [comment]
#236
