### ISSUE TITLE
Unable to save updated test

### ISSUE THREAD

**Issue by xvash** [jsperf/jsperf.com#275]
Save test case gives "Please review required fields and save again." after adding/modifying tests.

Even if I change any of the required fields, I get the same message.

![jsperf-bug](https://cloud.githubusercontent.com/assets/2887652/20538652/fd803ddc-b0a6-11e6-9030-052d4bba14cb.png)

**Comment by phistuck** [comment]
Me, too.
https://jsperf.com/membernullchecks/1/edit
https://jsperf.com/member-null-checks/1/edit
:(

**Comment by kof** [comment]
Confirm that. Was trying to save like crazy.

**Comment by demoneaux** [comment]
Duplicate of #236.

**Comment by mathiasbynens** [comment]
Closing as duplicate of #236.
