### ISSUE TITLE
Published checkbox dont works

### ISSUE THREAD

**Issue by yukulele** [jsperf/jsperf.com#286]
test case is published even if "publised" checkbox in not checked

**Comment by maxbeatty** [comment]
I was unable to reproduce using these steps:

1. add new test with "Publish" checkbox unchecked
2. view test saved correctly
3. look at [latest posts](https://jsperf.com/browse) and not see my new test
4. edit previously saved test to [now be published](https://jsperf.com/unchecked-publishes)
5. look again at latest posts to see just published test

If you had a different circumstance, please re-open with steps to reproduce.
