### ISSUE TITLE
jsperf.com is down again

### ISSUE THREAD

**Issue by louisremi** [jsperf/jsperf.com#289]
Hi! I'm a long term fan of JSPerf. I've just discovered it's down again: http://www.downforeveryoneorjustme.com/jsperf.com

I just checked closed issues as well as the official Twitter account and didn't see any message from the team. It'd be great if you could take the time to provide a bit of info about what's going on and if/when we can expect to see jsperf online again :-)

Thanks a lot for the great work!

**Comment by eperret** [comment]
@mathiasbynens , @maxbeatty , any idea when the site will be back up?

**Comment by maxbeatty** [comment]
We are working on an issue with the database and don't have a solid estimate on when it'll be fixed. I will update this issue when we know more.

We're also working on making the development of jsperf more sustainable to get these issues addressed faster. More soon.

**Comment by maxbeatty** [comment]
If you're in a position to sponsor jsPerf, please see #291

**Comment by maxbeatty** [comment]
Database issue has been resolved. Mathias is working on DNS configurations (complicated but know what needs to happen). Thanks for your patience.

**Comment by mathiasbynens** [comment]
jsPerf is now back up! https://jsperf.com/

**Comment by OliverJAsh** [comment]
It seems we're unable to create test cases due to
https://github.com/jsperf/jsperf.com/issues/257
