### ISSUE TITLE
GitHub OAuth error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by thomastuts** [jsperf/jsperf.com#29]
While I was trying to get the project up and running locally, I stumbled upon an error when performing the GitHub authentication part. This is the error in full:

```json
{
    "error": "redirect_uri_mismatch",
    "error_description": "The redirect_uri MUST match the registered callback URL for this application.",
    "error_uri": "https://developer.github.com/v3/oauth/#redirect-uri-mismatch",
    "state": "4Nz5n60BXDW9hoqlC9tjzv"
}
```

Per the README.md's recommendations, I had `http://localhost:3000/` (the same URL as the server) as the authorization callback URL, which resulted in this error.

Adding `127.0.0.1	dev.jsperf.com` to my `/etc/hosts` file and setting the callback URL to `http://dev.jsperf.com` managed to _somewhat_ fix the issue: I got the GitHub auth prompt, and it redirected me to `http://dev.jsperf.com/auth/github?code=XX&state=XX`. Finally, by adding the port manually to that URL, jsperf saved those credentials and I can now use the application (except for not having a BrowserScope API key, but that's another issue).

My question here is: have I done something wrong (which is entirely possible since my knowledge of OAuth is severely lacking), or is there something missing in the documentation? If there is, I'll send a PR your way to correct any documentation if you could me point in the right direction.

**Comment by maxbeatty** [comment]
I, too, had trouble setting up GitHub Auth locally. I thought it had something to do with hapi registering itself as `maxbeatty.local` instead of `localhost` (and thus causing URI mismatch). I think I originally [removed "localhost" mentions to run inside of docker](https://twitter.com/maxbeatty/status/564531545851981824)

Maybe @asilluron can share how he's setup

**Comment by asilluron** [comment]
Starting fresh to diagnose

**Comment by asilluron** [comment]
Using a fresh checkout, was not able to reproduce error. Here are the settings I am using:

```
NODE_ENV=development
SCHEME=http
DOMAIN=localhost:3000
PORT=3000
BROWSERSCOPE=replace
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASS=
DB_NAME=jsperf_dev
GITHUB_CLIENT_SECRET=<<redacted>>
GITHUB_CLIENT_ID=<<redacted>>
BELL_COOKIE_PASS=test
COOKIE_PASS=test
```

## GitHub Application Settings 
![screen shot 2015-06-29 at 12 04 16 pm](https://cloud.githubusercontent.com/assets/1937329/8437034/59e10c4c-1f11-11e5-8916-f0b4938542f9.png)

**Comment by thomastuts** [comment]
Cool, thanks for the quick reply. I'll try again later with a fresh repo and will update here.

**Comment by thomastuts** [comment]
Using your `.env` settings, I managed to track down where things went wrong. The `npm setup` defaults to `dev.jsperf.com` for the domain. Changing this to `localhost:3000` fixes the error, and I can now authenticate properly using GitHub.

Maybe it's better to set this default to `localhost:3000`, since that seems to work out of the box without having to fiddle with `/etc/hosts`? Just a thought.

**Comment by maxbeatty** [comment]
@asilluron thanks for outlining your setup. port in domain was key

@thomastuts just pushed up 811f7115d3e47672b8dda7f08284f4e548d369f8 to include non-80 ports in the domain so will hopefully be a little easier to work with but as I'm typing this I realize I'm going to break @asilluron's setup :facepunch: ok need to make this a little more robust
