### ISSUE TITLE
jsperf.com SSL Error

### ISSUE THREAD

**Issue by cjntaylor** [jsperf/jsperf.com#294]
The website seems to be unable to render right now, reporting an SSL protocol error across all major browsers (Chrome, Firefox, Safari and Edge).

Not sure if this is related to #289 or a side effect of the recent changes? Wanted to drop you all a note just in case. Thanks for the hard work!

**Comment by mathiasbynens** [comment]
Thanks for the help!

We’re working on getting jsPerf back up, using @zeit/`now` for the Node.js hosting and DigitalOcean for the MySQL database. Until then the site is down and TLS errors can be expected.
