### ISSUE TITLE
Tests are not editing correctly

### ISSUE THREAD

**Issue by wadewalker25** [jsperf/jsperf.com#300]
Editing & saving a test are not carrying the test cases over to the revised test case. And now there are about a half a dozen tests cases that do nothing what so ever.

I've tried multiple times to edit this test: https://jsperf.com/appending-to-an-array-push-apply-vs-loop/3
I'll click the 'edit these test cases...' which takes me to the above url with '/edit' appended.
I'll make a change to one of the test cases and hit the 'Save test case' button.
It will take me to a captcha screen where I'll hit the check mark stating I'm of human origin.
It will navigate me back to the edit screen with a message at the top stating
* Not all tests inserted

I'll hit save again, because WTF, and then the page will refresh where my changes are now lost. 
If I go back to the original page without the edit appended, https://jsperf.com/appending-to-an-array-push-apply-vs-loop/3, I'll see my revisions with no test cases.

**Comment by HolgerJeromin** [comment]
Thanks for reporting. This is already discussed as #236

**Comment by ainthek** [comment]
Sorry for asking: I just experienced this on jsPerf.com.
trying to edit https://jsperf.com/new-array-vs-splice-vs-slice/101/edit

Test with 11 tests enden up as new revision with just 1 test added.
 #236 says closed but it seems not fixed. Any hints ?

**Comment by kawazoe** [comment]
Same thing here. I tried to edit [https://jsperf.com/char-is-number](https://jsperf.com/char-is-number) only ended up creating new broken revisions.

**Comment by kylebakerio** [comment]
Also experiencing this. I wanted no revisions, and there used to never be. Now every attempt to save just makes a new broken revision.

https://jsperf.com/2015-vs-2018-comment-removing-code-challenge
