### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ricordisamoa** [jsperf/jsperf.com#302]
While the old https://github.com/mathiasbynens/jsperf.com was dual-licensed under MIT and GPL, I can't find any license statement pertaining to most of the code within this repository. I really hope it is an oversight and you didn't mean to make it proprietary...
(Also, it may seem that travis-ci.org is for open source repositories only?)

**Comment by mathiasbynens** [comment]
It was an oversight!

**Comment by ricordisamoa** [comment]
Thank you.
