### ISSUE TITLE
Allow a code snippet to be removed

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#309]
Currently, there is no UI element to remove a code snippet when creating or editing a test. A button that removes the DOM elements should do the trick.

**Comment by epicgirl1998** [comment]
+1-ing this

> A button that removes the DOM elements should do the trick.

i tried removing the snippet's `<fieldset>` element using chrome's dev tools but the snippet is still there after submitting the form

a working workaround would be appreciated

**Comment by Luchillo** [comment]
The faq says it can be done by deleting both the title and code of such snippet, however it doesn't work:

https://jsperf.com/faq#remove-snippet

**Comment by maxbeatty** [comment]
Sorry, that FAQ is outdated (can't leave inputs blank now that they are validated). I confirmed removing `<fieldset>` or individual inputs does not delete the test case.

**Comment by helmutgranda** [comment]
Is there a work around while this is being implemented?
