### ISSUE TITLE
Don’t create new revisions when editing a user’s own test during the same session

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#315]
Editing one of your own tests should not create a new revision. Only create a new revision when the test author != the current user.

**Comment by maxbeatty** [comment]
The title and description feel at odds to me. Now that we have GitHub auth, is session still how "current user" should be measured? 

Once `github_user_1` creates a page, should they always edit the same revision of the page?

I've been thinking more and more how to introduce proper "users" now that there's dedicated auth. Are revisions now like forking a repo (max/jsperf => mathias/jsperf)? that could open up possibilities for #252 (what have I done?)

**Comment by maxbeatty** [comment]
Basically, I think keeping all the PHP-Session-based logic and layering on GitHub auth is the real root of all the editing problems. It may be possible to plug the holes but would be better long term to flesh out a user concept

**Comment by mathiasbynens** [comment]
> Are revisions now like forking a repo (max/jsperf => mathias/jsperf)?

That would change the URL structure, which I’m opposed to.

> Once github_user_1 creates a page, should they always edit the same revision of the page?

Absolutely! GitHub users are the new sessions, basically. 👍

**Comment by dcodeIO** [comment]
In the meantime, this could be implemented by adding new revisions to a user's `own` session jar var when created. This should make it work while the session is still active.

**Comment by maxbeatty** [comment]
fixed by #325. now, new revisions are not created when the original author makes edits
