### ISSUE TITLE
Always load Google Analytics?

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#318]
What's the reasoning behind [conditionally loading Google Analytics](https://github.com/jsperf/jsperf.com/blob/9120572eb549fc1f7e3d16c8f3ddde6679d02e0b/templates/partials/footer.hbs#L109)?

**Comment by mathiasbynens** [comment]
They’re loaded on every page:

1. either through `main.js` https://github.com/jsperf/jsperf.com/blob/5a87b1bbe1bca7616ce741a3b9fe2955556ae8d4/public/_js/main.src.js#L137-L144
2. or by inlining the snippet you linked to.

Rationale: if we already load `main.js`, there’s no reason to add another `<script>` just for GA — we can load it from inside of `main.js`.
