### ISSUE TITLE
cant create tests because of bad captcha handling?

### ISSUE THREAD

**Issue by boynet** [jsperf/jsperf.com#322]
everytime I try to add\edit tests cloudflare take me to the captcha page - all good the problem is after completing successfully the captcha the form get reset and I need to refill the details(and then again redirected to captcha page after submitting) 

I don't know what side the bug is but please keep the form post after the captcha success

**Comment by maxbeatty** [comment]
Sorry you're running into issues with Cloudflare. Unfortunately, that's entirely separate from the application code here in this repository. Your best course of action may be to work with Cloudflare directly.

**Comment by grave-dancer** [comment]
Yes, it's *completely* cloudfare's fault, not jsperf's.. lol what fine user support
