### ISSUE TITLE
consider node-uap for user agent parsing

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#33]
> platform.js is in maintenance mode so I wouldn't mind handing off to uap-core by way of node-uap
> — [jdalton](https://github.com/jsperf/jsperf.com/pull/13#issuecomment-123924257)

platform.js is currently used on the client to display the visitor's browser's name and version along with the OS on test pages. could replace with [node-uap](https://www.npmjs.com/package/node-uap) on the server

**Comment by vladikoff** [comment]
uap is not getting updated well either, maybe https://github.com/3rd-Eden/useragent or something else?

**Comment by jdalton** [comment]
node-uap is just a wrapper around [uap-core](https://github.com/ua-parser/uap-core) which still has activity.

**Comment by vladikoff** [comment]
ah it seems like when I looked at it was inactive:

![](http://v14d.com/i/574f15eeb203c.jpg)

Seems they are back at it though, 👍
