### ISSUE TITLE
Can not remove code snippet

### ISSUE THREAD

**Issue by Minstel** [jsperf/jsperf.com#331]
Seems like currently removing code snippet is not working. I tryed to cleat `title` and `code` fields of snippet, and then save. After saving empty snippet still exists in editor, with message `Please enter a title for this code snippet`. And it is still working on `test run` page.

Tested on [this test](https://jsperf.com/best-remove-spaces/1)

**Comment by maxbeatty** [comment]
Known issue. See #309
