### ISSUE TITLE
Couldn't load main-20150701.js

### ISSUE THREAD

**Issue by wende** [jsperf/jsperf.com#34]
Right now there is a problem with loading a file named "main-20150701" and when adding a test suite, after clicking submit button nothing happens except for reloading of the page.

PS. There was a SSL Certificate problem while ago

**Comment by maxbeatty** [comment]
Just tried reproducing this and `main-20150701.js` is loading as expected. Perhaps there was a hosting hiccup. If you continue to see a problem, please reopen.
