### ISSUE TITLE
New code snippet was blocked on jsperf.com by Cloudflare

### ISSUE THREAD

**Issue by mhkrebs** [jsperf/jsperf.com#345]
I tried to add a code snippet to https://jsperf.com/string-concatenation/47/edit and was blocked for some reason:

> Sorry, you have been blocked
> You are unable to access jsperf.com

Here's what I tried to add:

    Title: Template literal
    Code: var foo = `${str1}${str2}${str3}{$str4}`;

The page suggested I should contact the site owner and include "Cloudflare Ray ID: 32f7e5954eff2aa9".  If this issue should be filed someplace else, please let me know, but this seemed like a reasonable place.

As an aside, it wasn't clear to me if newer Javascript standards were allowed (the above is ES6).  Might be worth a FAQ entry either way.

**Comment by mathiasbynens** [comment]
jsPerf doesn’t restrict the code you can enter in any way. ES2015 is definitely allowed.

I’m closing this as the reported issue is a false positive with Cloudflare filter. I’ll look into reducing the aggressiveness of our Cloudflare settings.

**Comment by vanowm** [comment]
I just got blocked message as well, when I had () in snippet titles. After removing parenthesis it went through.
