### ISSUE TITLE
Microsoft Edge 20 detected as Chrome 42

### ISSUE THREAD

**Issue by am11** [jsperf/jsperf.com#36]
I ran a test using Edge on Win10 (newly installed, no tweaks to UA-string, document/browser modes etc.), and it detected the browser as Chrome 48:
![image](https://cloud.githubusercontent.com/assets/3840695/9026676/3149e34a-38ec-11e5-8768-d254d6b157a0.png).

**Comment by jdalton** [comment]
This is a known issue in [platform.js](https://github.com/bestiejs/platform.js/issues).
