### ISSUE TITLE
Local installation copy doesn't run tests

### ISSUE THREAD

**Issue by geraldchecka** [jsperf/jsperf.com#37]
I've installed jsperf locally and things ran smooth on 'npm start'. However,
- I wasn't able to do 'Run Tests' on localhost:3000. No console errors.
- Looks like the app isnt picking up preparation code what I entered in the previous page.
- The above mentioned behavior is consistent with other public tests that I tried to run on this machine,
<a href="https://jsperf.com/obj-arr-comp">Test case</a> is the one.

Please find attached screenshot of the error page.
![jsperf error 1](https://cloud.githubusercontent.com/assets/5643210/9140530/89fcd076-3d4f-11e5-9963-c89584471126.jpg)

**Comment by maxbeatty** [comment]
`highlight` and `indent` from the screenshot are handlebar helpers most likely getting overly escaped. I haven't reproduced personally but this was part of the big changes in #13

**Comment by jfeltesse-mdsol** [comment]
Same here. 
Managed to setup and run the server, make a test case but accessing the page in chrome or firefox show the Ops/sec cells as "pending..." and clicking on "Run tests" does nothing.
No errors either on the server or the client side.

**Comment by maxbeatty** [comment]
Should have been fixed in https://github.com/jsperf/jsperf.com/commit/23ab90519fcac8d5fb3e2dc1d7d8438886b56c4f
