### ISSUE TITLE
Site always runs captcha page

### ISSUE THREAD

**Issue by dalisoft** [jsperf/jsperf.com#38]
Hi @jsperf!
I'm using jsperf and after restore snippets site not working properly!
I'm using Kaspersky Anti-Virus (Windows 10 Multiple Edition), Android 4.1.2 (SGS2) and iOS9 and all shows same page when applying improvements!
Note: When i writing any text like lorem ipsum its appling else shows captcha page, i sure on my pc hasn't virus/marlware!

Sorry for my bad english

**Comment by lukeb-uk** [comment]
I'm getting an issue with the captcha page showing every time I try to save a test. As a result of this page appearing, it discards the post data.

**Comment by rnicholus** [comment]
Same happening to me. But I'm on a Mac running Chrome - no A/V. Looks like there isn't a way to create a new perf at the moment.

**Comment by dalisoft** [comment]
I now know why it's that, jsperf checks every test case update doing people, not a BOTs! Remember, more site now attacking with bots, DDoS and other ways, captcha stops like that and highly security, optimizes performance (server request will be reduced)!!!
Sorry for bad english :(

**Comment by juhana** [comment]
@dalisoft The problem is not that the captcha exists, but that it doesn't work! Even if you complete the captcha you're redirected back to an empty form. (Same issue here as the others, Chrome on Mac.)

**Comment by dalisoft** [comment]
I trying update 2x and all fine now

**Comment by dalisoft** [comment]
Just he blocked my ip ;)

**Comment by designbyadrian** [comment]
:+1: for me too :(

Safari and Chrome on Mac.

**Comment by dalisoft** [comment]
Cloudflare blocked my IP?

**Comment by 0x24a537r9** [comment]
Yeah, unfortunately this is making jsperf unusable. I can't edit my test, and I've tried over a dozen times, waiting minutes in between attempts in the hopes of avoiding CloudFlare's overly zealous CAPTCHA-ing.

**Comment by dalisoft** [comment]
I have all account, example, GitHub, CloudFlare, Google and other.
Still, jsperf runs CloudFlare captcha. What i need to do to make performance test?
Please help or can you're give me HTML5 version of performance tester?

**Comment by pygy** [comment]
Same here, I keep being punished by both ReCAPTCHA (often several image series) and the Cloudflare (first house numbers (often blurry but not too hard) and now mixed case, jumbled wordoids in a hollow font (very hard)).

Often ultimately, I end up losing the changes, and the multi-input nature of JSPerf makes it impossible to save and restore changes out of band.

Firefox + OS X as my main browser, but I usually check the WIP benchmarks from other browsers on the same machine. JSPerf user name Potator if it can help you help me...

**Comment by jfriend00** [comment]
Same here.  I've pretty much given up on jsperf any more as it's entirely unusable.  The other day, it threw away my changes 5 times before I finally got the blasted thing to let me through the captchas.  The general flow is that I get the picture captcha (which are often too small to discern what the images actually are), then I get the enter the letters in the image captcha, then without any errors, I'm throw back to my jsperf with all the changes I just made thrown away.  It's an absolutely horrible user experience.  If you're trying to get people to stop using your site, this is a pretty darn good way to do that.  It's really, really broken.

**Comment by jdalton** [comment]
We get it, it's broken, but at this time unless you're volunteering to fix it I'm not interested in your comments.

**Comment by pygy** [comment]
At last this is acknowledged :-)

I may be interested in improving the situation but it may require access to the server logs. I'll check the source tonight to check if ReCAPTCHA is correctly implemented.

Could you leave the issue open while the problem persist?

**Comment by pygy** [comment]
```
Searching 140 files for "recaptcha"

0 matches across 0 files

Searching 140 files for "6Leq-wgTAAAAANlo0hSQ80FvRMwjULZYYwFv-sma"

0 matches across 0 files
```

The `recaptcha` implementation is not public. Short of redoing it from scratch, there's nothing I can do to help right now.

The only thing that must be kept secret is the so-called 'secret key'. Everything else can be public. You could put out of the git repo on the file system, so that `require("../../../secret/key.js")` returns it.

**Comment by pygy** [comment]
@jdalton What gives? You can reach me by email: py@py.gy

**Comment by pygy** [comment]
Pinging @mathiasbynens as well.

**Comment by mathiasbynens** [comment]
@pygy The recaptcha implementation is not part of v2, and doesn’t need to be (I hope) since it uses GitHub Login.

The open issues blocking the v2 release are here: https://github.com/jsperf/jsperf.com/milestones/v2

**Comment by pygy** [comment]
Aaaahh... Now it makes sense... I thought that it was already live. I'll have a look at these.

**Comment by dalisoft** [comment]
There seem captcha is not JSPerf issue, a CloudFlare security issue and it need fix to work sites running CDN via CloudFlare! Maybe i'm wrong!

**Comment by dcharbonnier** [comment]
what pain... get away from CloudFlare this service just don't work...
