### ISSUE TITLE
About the "Preparation code"

### ISSUE THREAD

**Issue by mrdulin** [jsperf/jsperf.com#380]
Here is my test:
https://jsperf.com/object-assign-vs-immutable

I setup two `object`:
```js
var base = {status: "good", hypothesis: "plausible", errors: 0};
var ext = {status: "funky", hypothesis: "confirmed"};
```

and three `test runners`.

My question is the two `object` changed by first `test runner`, whether or not the rest `test runner` 
will use the two `object` which changed by my first `test runner`?

Or, to every `test runner`, always use my initial setup?

**Comment by mathiasbynens** [comment]
https://jsperf.com/faq#setup-teardown

The setup is run before each clocked test loop. In your example, all but the first iteration in each clocked test loop loop get the modified object.

**Comment by mrdulin** [comment]
@mathiasbynens Thanks for reply. You mean each `test runner` use the original setup data - `base` and `ext`, they are isolated?
