### ISSUE TITLE
use performance.now?

### ISSUE THREAD

**Issue by greggman** [jsperf/jsperf.com#40]
I assume this was considered but I don't see anything in the issue or the repo

https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

http://caniuse.com/#search=performance

**Comment by jdalton** [comment]
It's covered in a couple of issues. I'll add a reference in a bit (power out atm)

**Comment by mathiasbynens** [comment]
Rationale for not including `performance.now` in Benchmark.js: https://github.com/bestiejs/benchmark.js/commit/a9f397e5cd775a50e2ea49689f43088a2dfcc6f3#commitcomment-5431323
