### ISSUE TITLE
Unable to add test cases

### ISSUE THREAD

**Issue by ljharb** [jsperf/jsperf.com#401]
I get an error "not all test cases inserted", but then it does publish some (but not all) of the test cases in the form.

**Comment by maxbeatty** [comment]
#236

**Comment by ljharb** [comment]
Thanks - that issue dates back to October. Any chance it could be looked at soon, given that it basically drives the primary use case for jsperf?

**Comment by mathiasbynens** [comment]
@ljharb I likely won’t be able to look into this soon. We’re open to pull requests, though!
