### ISSUE TITLE
www.jsperf.com broken

### ISSUE THREAD

**Issue by daguej** [jsperf/jsperf.com#418]
[https://**www**.jsperf.com/](https://www.jsperf.com/) returns a CloudFlare SSL handshake error  (https://jsperf.com/ works fine).

**Comment by alundiak** [comment]
I can confirm it's still reproduced.

**Comment by Mattwmaster58** [comment]
Confirmed

**Comment by maxbeatty** [comment]
Please use https://jsperf.com as the canonical URL 😸
