### ISSUE TITLE
Better debugging / repeated editing story

### ISSUE THREAD

**Issue by msegado** [jsperf/jsperf.com#42]
It's currently difficult to iterate on test development since (1) you're required to complete one (sometimes two!) captchas before seeing the results of a change, and (2) the test and results are on separate pages.

Just adding a 15 minute grace period between captchas would really help, though a better editing/debugging story overall would be nice.

Thanks for the site!

**Comment by jdalton** [comment]
This is no longer the case in v-next.

**Comment by msegado** [comment]
Great, thanks!
