### ISSUE TITLE
All cases lost after update

### ISSUE THREAD

**Issue by Hollander** [jsperf/jsperf.com#423]
https://jsperf.com/yet-another-quicksort-right/3

I updated revision 3 and lost all test cases.
After Save I see 'Please review required fields and save again.'

**Comment by maxbeatty** [comment]
I see 2 cases for revision 3. Can you expand on what you mean when you say "lost all test cases"?

This may be related to #236

**Comment by Hollander** [comment]
Look, revision 3 dated 2013. You can start reproducing from this revision, as I did. 

- I pressed edit, 
- Changed  some code lines, 
- pressed save 
- Saw a message 'Please review required fields and save again.'
- checked that everything is fine
- pressed save again
- got new revision without any test cases. 

After that I tried to add some test cases, but it did't help - look at revisions 8 and 9.

**Comment by maxbeatty** [comment]
Yes, this sounds like #236
