### ISSUE TITLE
https

### ISSUE THREAD

**Issue by jimmywarting** [jsperf/jsperf.com#43]
its good that you support https but browserscope doesn't

And that's why it sometimes fails to load javascript (jsonp)

    Loading cumulative results data…
    The get/post request has failed :(

options are:
- change http://www.browserscope.org => https://ua-profiler.appspot.com
- disable https,
- tell browserscope to get ssl suppport
- or build your own proxy or use a third party

https://jsonp.afeld.me/?url=http%3A%2F%2Fwww.browserscope.org%2F%3Fcategory%3Dusertest_ahBzfnVhLXByb2ZpbGVyLWhychELEgRUZXN0GICAgJfZ_qAIDA%26v%3D3%26tqx%3DreqId%253A80%26o%3Djson

**PS** browserscope have json format aswell so you don't have to use insecure jsonp, the only thing you need is some CORS & https proxy witch https://jsonp.afeld.me offers

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/jsperf.com/issues/211 https://code.google.com/p/browserscope/issues/detail?id=356

**Comment by mscdex** [comment]
It looks like (and [according to the maintainer](https://groups.google.com/d/msg/browserscope/vziLgMLIA04/5E-FxPqLGQAJ)) development on browserscope has more or less stopped, so if jsperf could implement some solution that would be great. Being able to see results from other browsers is very helpful.

**Comment by mathiasbynens** [comment]
As of today, Browserscope now supports HTTPS (through Cloudflare’s Universal SSL)!
