### ISSUE TITLE
Cannot create a test case with more than 20 snippets

### ISSUE THREAD

**Issue by goibon** [jsperf/jsperf.com#432]
If I create a test case with 20 snippets everything seems to go well and I can save them, publish the case and run the snippets.
However, if I attempt to add any more snippets beyond the 20 then I get an error response and the edit page just tells me to "review required fields and save again."

I cloned the repo and ran a local copy where I reproduced the issue and I can see in the server log that when I attempt to save the test case Joi validation fails [at this line](https://github.com/jsperf/jsperf.com/blob/master/server/web/edit/index.js#L81).

The peculiar thing is that the first time I attempt to save the test case the validation error is: 

> [log,error] message: child "test" fails because ["test" must be an array], stack: ValidationError: child "test" fails because ["test" must be an array]

Looking at the data, `test` is an `Object` and not an `Array`.

Now if I attempt to save again I get a different validation error complaining that the id of snippet 21 is invalid:

> [log,error] message: child "test" fails because ["test" at position 20 fails because [child "testID" fails because ["testID" must be a number]]], stack: ValidationError: child "test" fails because ["test" at position 20 fails because [child "testID" fails because ["testID" must be a number]]]

Looking at the data, the `testID` property of snippet 21 is `''`.

Now when I try to delete the last snippet because cannot save the test case with it, I clear out the 'title' and 'code' input fields and save again in hopes that it will be deleted, but I just get the same error. So I cannot even return to the working state where there were only 20 snippets.

So my question is then:
Is it allowed to have more than 20 snippets in a test case or is it expected that it should fail?
If it is not allowed then the user should be informed more clearly and it should be possible to delete cases.

**Comment by maxbeatty** [comment]
> Is it allowed to have more than 20 snippets in a test case or is it expected that it should fail?

After a quick search, I didn't find "20" hardcoded anywhere relevant so it should be "allowed" but that strikes me as a high number of variations to be testing. Maybe there should be some sort of limit.

**Comment by goibon** [comment]
@maxbeatty I agree that it is a high number of snippets and it would likely make sense to have well defined and properly handled limitation rather than a 'coincidental limit'.
