### ISSUE TITLE
jsperf.com seems to have been taken over by movie pirates

### ISSUE THREAD

**Issue by ibrahima** [jsperf/jsperf.com#436]
The main page is full of links that appear to be referencing pirated movies, and clicking on any of them redirects to filmbuzz.top, which appears to be a pirate movie site.

**Comment by maxbeatty** [comment]
Thanks for the spam report. Assigning to @mathiasbynens to clean up

**Comment by waqast** [comment]
Add "Report Error" functionality. It might help to clean bogus and/or problematic codes.

**Comment by krausekai** [comment]
As referenced above, this is an unsanitized XSS attack from the comments.

**Comment by mathiasbynens** [comment]
The spam issue is #232.

@krausekai jsPerf by design allows anyone to submit JS to be executed. Nothing on jsPerf is an XSS attack.

**Comment by krausekai** [comment]
@mathiasbynens I disagree. This is originating from the comments section - not a test case. Additionally, test cases may need to prevent redirect functionality.

**Comment by ThomasRooney** [comment]
Definitely XSS. Here's one I copied from curling `https://jsperf.com/array-vs-set-delete-filter-complexity`

```
  <div id="comments-wrapper">
      <article id="comment-1" >
        <p class="meta">
          <img src="https://gravatar.com/avatar/bf4deb8b3236b33ac29c8990661fadee?s=26" width="26" height="26">
          <a href='https://github.com/masjokoo' rel='nofollow'>fghf</a>


          commented <time datetime="2017-11-03T16:28:54.000Z" pubdate>3 days ago</time>: <a href="#comment-1" title="Permanent link to this comment">∞</a>
        </p>

        <div><script language="javascript">
window.location.href = "http://filmbuzz.top/signup.php"
</script></div>
      </article>
  </div>
```

**Comment by mathiasbynens** [comment]
Oh, I missed the fact that this happens in the comments. I agree that shouldn’t happen! The original jsPerf v1 didn’t do this. Basic Markdown should be allowed in comments, but no HTML.

**Comment by Haroenv** [comment]
https://jsperf.com/native-xhr-vs-jquery-ajax is another example

**Comment by MisterZeus** [comment]
Pirate stuff on Popular JSPerfs page still happening today :-(

**Comment by acdcjunior** [comment]
Another example: https://jsperf.com/domparser-vs-createelement-innerhtml-vs-others/
