### ISSUE TITLE
Editing tests almost does not work at all

### ISSUE THREAD

**Issue by vitaliylag** [jsperf/jsperf.com#448]
I don't think the description is needed. Just try to edit anybody tests and you will be shocked. Firefox 56.

There are many and many bugs:
1. After saving old snippets are deleted
2. After saving it tells "Not all tests inserted" but actually it is saved. I pressed the button 5 times and 5 revisions were created.
3. If you edit some old snippet (title AND body) then it tells "Please review required fields and save again." and nothing is saved.
4. When you add new snippets it's order is mixed. You try to create new revision but old snippets are deleted and new snippets are mixed again.
5. When you edit not published revision new revision is created. I don't want to create new revision.
6. When you edit your own published test (first revision) new revision is not created but first revision is edited. I don't want to edit already published revision.
7. Or better I would like to see 2 buttons: "Edit current revision" and "Created new revision based on current revision".
8. I cannot unpublish accidentally published revision. I would like to have one hour to cancel my publishing.

**Comment by maxbeatty** [comment]
#236
