### ISSUE TITLE
Test shows both competitors fastest 

### ISSUE THREAD

**Issue by itaditya** [jsperf/jsperf.com#458]
![image](https://user-images.githubusercontent.com/15871340/34930064-937b3ea0-f9ed-11e7-9610-5d8c06911f89.png)

When I ran the test from https://jsperf.com/switch-vs-if-statements
both the competitors if and switch shows fastest when switch is faster.

**Comment by maxbeatty** [comment]
Those come from Browserscope so better to bring that to their attention. The variance percentages make each overlap which could explain both being considered fastest (283M - 2.58% intersects with 277M + 1.44%)

**Comment by mathiasbynens** [comment]
This is the result of running a test, and does not come from Browserscope. I’ll remove that part of your comment to avoid confusion :)
