### ISSUE TITLE
ER_CON_COUNT_ERROR: Too many connections

### ISSUE THREAD

**Issue by ferrybig** [jsperf/jsperf.com#459]
When trying to save my test case, I get `ER_CON_COUNT_ERROR: Too many connections`

No fields get highlighted with a red border, so it's unclear what the user should do to fix his fiddle.

JSperf should give clear explanations for their errors.

**Comment by maxbeatty** [comment]
this sounds like a database error 😕 we don't currently report errors to a service like Sentry or Rollbar in production but we should 😬

**Comment by Karolusrex** [comment]
I've had this for several days

**Comment by PeterGrayCreative** [comment]
I noticed this today too. Any word on when this issue might be fixed?

**Comment by Ninja4Code** [comment]
This looks like a MySQL error.  Please refer to this page: https://dev.mysql.com/doc/refman/5.5/en/too-many-connections.html

**Comment by JoshuaWise** [comment]
I've also been having this issue for several days.

**Comment by maxbeatty** [comment]
Our database server ran out of disk space. We have upgraded the server and restarted mysql

**Comment by Ninja4Code** [comment]
I can verify that I can now create, save and run new test cases.

Thanks!

**Comment by mathiasbynens** [comment]
@maxbeatty is a hero!

**Comment by dfcreative** [comment]
Still getting the same message 
![image](https://user-images.githubusercontent.com/300067/36572180-4a9062fe-1808-11e8-9974-ac1ad483e04d.png)

**Comment by maxbeatty** [comment]
Unclear why the database shutdown but it has been restarted

**Comment by ash-crash** [comment]
Can you do it again, seems like issue is back

**Comment by omixen** [comment]
hello, this is happening again. Can you restart again? thanks!

**Comment by maxbeatty** [comment]
I checked the database, and it is healthy. I'll try to find some time later today to investigate more. Thanks for your patience.

**Comment by jcoleman-techempower** [comment]
Currently getting this same issue

**Comment by mdownes** [comment]
me too
