### ISSUE TITLE
Trying to browse the test cases page errors with a time out

### ISSUE THREAD

**Issue by Nehon** [jsperf/jsperf.com#460]
Something seems wrong on the whole site
As the title mention, when clicking on the test cases link at the top of the main page you are given this error after a while 
` Error 524 Ray ID: 3e74cb2bab0068d2 • 2018-02-03 10:45:52 UTC
A timeout occurred` 
Also posting a test case ends up in the error already reported here : https://github.com/jsperf/jsperf.com/issues/459

and when trying to see existing tests you are given a page with an error "something went wrong" on top
https://jsperf.com/native-map-versus-array-looping
https://jsperf.com/map-vs-native-for-loop/7
https://jsperf.com/for-vs-foreach/268

**Comment by sam-s4s** [comment]
Yep - it's dead :P

**Comment by maxbeatty** [comment]
https://github.com/jsperf/jsperf.com/issues/459#issuecomment-363657708
