### ISSUE TITLE
"something went wrong"

### ISSUE THREAD

**Issue by mesqueeb** [jsperf/jsperf.com#462]
Dear Jspref.

I want to test the fastest way to filter some json data.
I have some simple setup, but I'm having problem saving my test.
Every time it says: "something went wrong"

I think maybe my preparation code is too long?
My objects i'm trying to upload are about 21,000 lines long.

**Comment by patelmitul** [comment]
As of now, 22-Feb-2018 12:40 CST, everything is "something went wrong". Can't access any test cases.

**Comment by maxbeatty** [comment]
No. You're likely seeing this because of that 21,000 line upload. I'm sorry there aren't any "limits" documented.

**Comment by mesqueeb** [comment]
@maxbeatty What is the limit?

**Comment by maxbeatty** [comment]
If I knew them, I’d document them 😿

**Comment by mesqueeb** [comment]
@maxbeatty 😭
