### ISSUE TITLE
Copyright / intellectual property issues

### ISSUE THREAD

**Issue by tombailey** [jsperf/jsperf.com#469]
This is more of an issue with jsperf.com itself rather than your codebase here on Github. You seem to have a copyright issue, just take a look at recent under popular and you will see things like:

- iTools 4.3.3.5 Portable Crack
- Tom Clancy's Rainbow Six Siege: Operation Chimera Crack CODEX SKIDROW
- etc

See https://jsperf.com/qxtcxbxmb for a concrete example.

You might want to take a look at that. Maybe you should add the ability to "report" test cases like these?

**Comment by maxbeatty** [comment]
Yes, spam is an ongoing issue. #232 outlines some good solutions but, alas, they haven't been implemented
