### ISSUE TITLE
Add ability to have a verification step

### ISSUE THREAD

**Issue by Eibwen** [jsperf/jsperf.com#47]
Have a step, basically in Teardown phase, that can verify the finished result of each of the tests.

I'd imagine we might be able to do it in Teardown somehow, but i'm not seeing any documentation on how to right now.

**Comment by jdalton** [comment]
Hi @Eibwen! This gets tricky to nail down. So far we've punted on allowing devs to do this at any point during their test (in the prepare or setup or teardown). I don't want to get into the unit test space with this.

**Comment by Eibwen** [comment]
Well just incase someone finds this in the future, I believe if you wanted to do this you can:

1. Use a global variable
 1. Then verify in the teardown step
 1. ~~Make sure to reset it at the start of each test case `output = undefined;  <your code>`~~
    1. Since the timing runs get run repeatedly, this method only ever checks the output of the final run
 1. This is the best way for timing, since no extra time is added to the test cases
 1. This will NOT work for async enabled tests, since global variable being shared
1. Use a validation function, and assume it will run in consistent time
  1. This will add the validation time to every test, and every single output will be tested to be valid
    1. This slows down each op, so the ops/Sec will become normalized here
    1. For those reasons the timing results of tests written in this fashion are as reliable
