### ISSUE TITLE
Ad Blockers break site

### ISSUE THREAD

**Issue by ianwremmel** [jsperf/jsperf.com#479]
It looks like carbon ads is part of the critical path, so if you've got uBlock Origin or Firefox Tracking Protection enabled (I believe it's enabled on all sites by default), login appears to fail silently.

**Comment by mathiasbynens** [comment]
We use GitHub OAuth for login.

Carbon Ads is not part of the critical path; that would be terrible.

**Comment by ianwremmel** [comment]
Agreed. I wasn’t able to login until I turned off both ad blockers. The carbon ads failure was the only console error, hence my suggestion that it was in the critical path.

**Comment by ianwremmel** [comment]
Actually, I should say, the logged in ui didn’t render until I turned off the adblockers. I may have been successfully authors with GitHub.
