### ISSUE TITLE
Slug validation not working properly

### ISSUE THREAD

**Issue by anurbol** [jsperf/jsperf.com#486]
The error occurs when trying to create a new test case.

this works: one-hyphen
this won't work: two-hyphens-slug

**Comment by maxbeatty** [comment]
Did you have a trailing space by chance? [Here's the regex we use for slugs](https://github.com/jsperf/jsperf.com/blob/261811d8000b4da6c5a26ab1b6d0f4c51bd39195/server/lib/regex.js#L87) and your case of `two-hypens-slug` passes. Please reopen if someething else is causing it to fail.

**Comment by anurbol** [comment]
Hi, @maxbeatty ! Yes, your regex is correct. But here's algorythm of reproducing (every-time for me):
1. Add any title and other data
2. Add this slug: proxy-vs-getset-vs-object-define-property-setting-a-value
3. Create test case
Expected behavior: test case created
Actual behavior: test case not created, with validation error next to the "slug" input field showing: `The slug can only contain alphanumeric characters and hyphens.`

I am using Google Chrome 67, OS: Lubuntu
