### ISSUE TITLE
Sorry, you have been blocked

### ISSUE THREAD

**Issue by scf37** [jsperf/jsperf.com#488]
When opening this page:

https://jsperf.com/eval-vs-script-tag/2
Cloudflare Ray ID: 4581fbd9285e34b2

This url works well for me: https://jsperf.com

**Comment by maxbeatty** [comment]
Sorry, we have very little control over Cloudflare's blocking

**Comment by vanowm** [comment]
Is there any specific reason why this happening ONLY on this website?
(for me this happening when I'm trying submit a new test)

**Comment by scf37** [comment]
Because of cloudflare XSS protection, it filters out specific javascript code.

**Comment by munrocket** [comment]
Cloudflare Ray ID: 53dc5e580f7bd709

**Comment by DmitryEfimenko** [comment]
I'm getting blocked when trying to add a third-party library to the test. For example, when clicking on the jquery to add corresponding script. Just that automatically blocks me

**Comment by munrocket** [comment]
@DmitryEfimenko just try https://www.measurethat.net/Benchmarks/

**Comment by meetDeveloper** [comment]
I have been blocked too, I think you guys need better developer to know who is harmful and who is not, I was just adding another test cases. You lost one person,

**Comment by hybridview** [comment]
What a bummer. I really liked using this service. Now cannot edit anything.

**Comment by scf37** [comment]
Renamed ticket because I get heart attack every time I receive new email "Sorry, you have been blocked"

**Comment by Finesse** [comment]
> Because of cloudflare XSS protection, it filters out specific javascript code.

...on a website designed to receive a JS code to run in browser 🤦‍♂️

**Comment by amsul** [comment]
Just happened to me as well..guess I can't use jsperf anymore. @Finesse thanks for the suggestion!

**Comment by meetDeveloper** [comment]
@maxbeatty You seriously want people to go away from jsperf because of your cloud provider ?

**Comment by maxbeatty** [comment]
@meetDeveloper please be respectful and constructive with your comments.

**Comment by meetDeveloper** [comment]
@meetDeveloper I meant people are commenting on this ticket and you are taking no action.
