### ISSUE TITLE
Broke the site + XSS vulnerability

### ISSUE THREAD

**Issue by sanderd17** [jsperf/jsperf.com#489]
I tried editing a test, but changed the name from "getElementsByClassName vs querySelectorAll" to "getElementsByClassName vs querySelector", as I only wanted to get the first returned result.

Apparently, this test already existed (though not in the form I liked). And submitting the test under that name caused some weird issues:

* There were no tests committed
* The revision numbers add up from the original test, but are shown under the new name
* The HTML is leaked into the main interface (and scripts defined there are executed on load). See the bottom of the page

Original test I wanted to edit: https://jsperf.com/getelementsbyclassname-vs-queryselectorall/25
Test I ended up with: https://jsperf.com/getelementsbyclassname-vs-queryselector/274

**Comment by mathiasbynens** [comment]
I'm not sure I understand the "XSS vulnerability" part. The whole point of jsPerf is to run arbitrary user-supplied JavaScript.

**Comment by sanderd17** [comment]
It's expected to run arbitrary user-supplied JS when running the benchmarks.

This normally enables the user to open the page first, then inspect the code (code should be inspected anyway, to confirm the benchmarks actually test what the user wants to know). At that point, the user can safely run the code.

But apparently, the HTML is leaked to the bottom of the page, including any script tags. This means scripts can run before the user gets the opportunity to check the code. At this point, malicious code could f.e. redirect the user, or try to steal login tokens.

Anyway, I should have researched this better, as it appears to happen on every page, and the "not saving the tests" also seems to be another issue.

I guess I should close this one, as it's not constructive.

**Comment by mathiasbynens** [comment]
Yeah, inserting arbitrary HTML (including `<script>` tags) is another intentional feature. It maps to the "Preparation code" section in the input form. We even have a UI that inserts `<script>` tags for popular libraries for you. Sure, it could be abused, but this is working as intended.

**Comment by mathiasbynens** [comment]
> At this point, malicious code could f.e. redirect the user, or try to steal login tokens.

If you really found a way to really steal login tokens just by creating a jsPerf test and getting a logged-in victim to open it, that's a bug. This should not be possible.
