### ISSUE TITLE
I see only 404 pages when going to tests and profile

### ISSUE THREAD

**Issue by YonatanKra** [jsperf/jsperf.com#494]
Hi,
I'm getting to a 404 page when going to tests I've written a while ago. 
Example: https://jsperf.com/bitwise-vs-optimized-boolean
Any idea why?
Thanks!

**Comment by maxbeatty** [comment]
I just confirmed that slug isn't in the database. There's a very, very small chance it could have been accidentally purged with our ongoing spam problem. I did find 3 tests from 2015 that look like yours. If you email me, I could share those with you

**Comment by YonatanKra** [comment]
Got it - thanks a lot for the offer. The 2015 ones I don't even know what they were.
I've created new ones this year for a blog post I'm about to publish and the links were dead.
Luckily, google has caching so I've just recreated it: https://jsperf.com/bitwise-vs-boolean-data-handling/1
Thanks again!
