### ISSUE TITLE
AWS permissions error when removing test cases

### ISSUE THREAD

**Issue by jlisee** [jsperf/jsperf.com#497]
Thanks for making an awesome site, I have this test: https://jsperf.com/protobuf-js

And I am trying to remove test cases that are not applicable, but I get this error in red at the top of the page:

```
ER_TABLEACCESS_DENIED_ERROR: DELETE command denied to user 'zeitdaemon'@'ec2-52-53-220-174.us-west-1.compute.amazonaws.com' for table 'tests'
```

**Comment by maxbeatty** [comment]
Sorry about that. I will check grants for that user in mysql and update this issue with what I find

**Comment by maxbeatty** [comment]
ok try it now. please reopen if still not working as expected
