### ISSUE TITLE
Java NPAPI Disabled in Chrome 09/2015, IE Edge

### ISSUE THREAD

**Issue by skibulk** [jsperf/jsperf.com#51]
I reveived this notice in the latest version of Chrome. https://support.google.com/chrome/answer/6213033

Your "cumulative data results" were not displayed, I assume as a result of this error.

**Comment by skibulk** [comment]
Using IE Edge, Java also gave an error and pointed to this page:

http://java.com/en/download/help/jcp_security.xml

**Comment by d10** [comment]
The plugin is basically a small Java applet which allows us to use Java timers in order to measure timings more accurately. However it is an enhancement and is not strictly required.

The data not being displayed is due to a separate error: https://github.com/mathiasbynens/jsperf.com/issues/211.
