### ISSUE TITLE
Configured to block Japan?

### ISSUE THREAD

**Issue by greggman** [jsperf/jsperf.com#517]
I'm in Japan, everytime I try to save a test I get the captcha. I just edited a test about 20 times working through some bugs and every single time the captcha showed up. Fortunately only one of those 20 times did it present a full puzzle.

Is there anything to do or am I just out of luck. I read the [faq](https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor-) in cloudflare and checked my IP address was not on any lists (it's not).

Fortunately I never lost any work

**Comment by maxbeatty** [comment]
Sorry, we know this sucks, but it's outside our control. Please read https://github.com/jsperf/jsperf.com/issues/518#issuecomment-570938579
