### ISSUE TITLE
Blocked for no reason

### ISSUE THREAD

**Issue by fabiochelly** [jsperf/jsperf.com#519]
I'm trying to add a simple snipper to an existing test and I get a "Sorry, you have been blocked" error.

Link to the test :
https://jsperf.com/filter-map-vs-reduce-concat-vs-reduce-push/

Here is my code :
`things.flatMap(e => e.selected ? [e.id] : []);`

The footer :
Cloudflare Ray ID: 54fc9942dae3cddb

My IP is a normal french IP, no proxy.

**Comment by asilluron** [comment]
The test you linked works for me, are you saying that you are blocked on that link?

OR

does it block when you try to add something?

**Comment by fabiochelly** [comment]
Yes. I'm blocked when I click on "save" whenever I'm adding to an existing
link or creating a new one.

Fabio

**Comment by maxbeatty** [comment]
Sorry, we know this sucks, but it's outside our control. Please read https://github.com/jsperf/jsperf.com/issues/518#issuecomment-570938579
