### ISSUE TITLE
Move test

### ISSUE THREAD

**Issue by minitauros** [jsperf/jsperf.com#52]
Would be really cool if you could re-order the tests. When I have a bunch of tests and I discover that I forgot to add one somewhere, there's no way for me to add a new test and say "this one should come after THAT test".

**Comment by maxbeatty** [comment]
Sorry, I don't follow. Can you give an example with some code?

**Comment by minitauros** [comment]
Yes I can, but I think reformulating my case might also help. When creating a test case and you add let's say 3 tests, save it, check it, run it, and then discover "oh shit I want to add a 4th test, but it shouldn't be the last test in the bunch", there is no option to add it in a custom position - it will always become the last test.

Example:
Test 1: test queryselectorAll
Test 2: test querySelector
Test 3: test jQuery selector
Test 4: test getElementsByTagName

Oh fuck I wanted test 4 to be at the positon of test 3, and test 3 should be the last. Ok I'll have to cut/paste evyerthing because I can't reorder them :(.

**Comment by maxbeatty** [comment]
Is this purely for aesthetics? Test ordering shouldn't impact results. If it is, you should refactor those tests.

**Comment by minitauros** [comment]
It does not impact test results :). Just not sure where else to leave this thought.

**Comment by mathiasbynens** [comment]
For now we’re not planning on adding new UI features to jsPerf. The current focus is to get v2 live asap.

@minitauros Have you considered creating a userscript / browser extension to do this?

**Comment by minitauros** [comment]
Roger that, looking forward to it! I haven't, but thanks for the tip!
