### ISSUE TITLE
Cloudflare keeps denying requests because they contain <script>

### ISSUE THREAD

**Issue by dangeredwolf** [jsperf/jsperf.com#522]
step 1: include a <script> tag in the setup html
step 2: fill out other information
step 3: click save
step 4: cloudflare displays the following message:
![Screenshot_1145](https://user-images.githubusercontent.com/2636265/72560580-5369e780-3875-11ea-9c6a-880ddf230507.png)

**Comment by maxbeatty** [comment]
Sorry, we know this stinks but not much we can do about it. See #518 for more
