### ISSUE TITLE
CloudFlare rejects my benchmark

### ISSUE THREAD

**Issue by willydee** [jsperf/jsperf.com#523]
## Steps to reproduce
Include preparation code:
```<script src="//cdnjs.cloudflare.com/ajax/libs/ramda/0.25.0/ramda.min.js"></script>```
## Expected result
Library should be included, benchmark should be executable
## What happens instead
Sorry, you have been blocked
Cloudflare Ray ID: 56827b1b0c588c92

**Comment by maxbeatty** [comment]
https://github.com/jsperf/jsperf.com/issues/518#issuecomment-570956196
