### ISSUE TITLE
[IMPORTANT] Migrate from Zeit 1.0 config to Vercel config

### ISSUE THREAD

**Issue by Richienb** [jsperf/jsperf.com#534]
This is essential to prevent the website from returning HTTP 500 errors.

Related to #495, #512, #529 and #531

// @maxbeatty @mathiasbynens

**Comment by zba** [comment]
seems https://jsperf.com not works anymore.
![image](https://user-images.githubusercontent.com/807956/91031282-8efa3a80-e62a-11ea-8b77-735aaf1022b7.png)

**Comment by asilluron** [comment]
Okay, on it.

**Comment by AliMD** [comment]
whatsup ? 👀

**Comment by asilluron** [comment]
Being handled here: #535

**Comment by Richienb** [comment]
@asilluron Houston, we have a problem.

![Directory listing](https://user-images.githubusercontent.com/29491356/92683212-68f0cc00-f386-11ea-8693-abf090188719.png)

**Comment by Slapbox** [comment]
Indeed we do have a problem. ![image](https://user-images.githubusercontent.com/6835891/92809286-7a3bd780-f38a-11ea-9d0d-396407b96488.png)

A _huge_ thanks to the maintainers working to get JSPerf back up and running!
