### ISSUE TITLE
The path '/browse/{authorSlug}' does not work

### ISSUE THREAD

**Issue by styfle** [jsperf/jsperf.com#55]
The FAQ says the following:

> **How can I keep track of new or updated test cases made by a specific user?**
> Every author has its own Atom feed, located at http://jsperf.com/browse/author-name.atom. Omit the .atom suffix to get a clickable list instead. If you’re identified on jsPerf (i.e. if you’ve commented, or created/edited a test case), a “My tests” link will appear in the navigation.

The [source code](https://github.com/jsperf/jsperf.com/blob/master/server/web/browse/index.js#L65) appears to support this feature.

However these URLs just redirect to the home page
* https://jsperf.com/browse
* https://jsperf.com/browse/styfle
* https://jsperf.com/browse/styfle.atom

I recently [created a test](http://jsperf.com/conditional-console-log) under the name "styfle" in case my other tests were deleted, however still no luck.

**Comment by maxbeatty** [comment]
jsperf.com is still running [the old PHP version](https://github.com/mathiasbynens/jsperf.com)

**Comment by mathiasbynens** [comment]
This has been disabled on the old version. When we switch to v2 it will magically start working again.

**Comment by styfle** [comment]
When is the switch to v2 happening?
