### ISSUE TITLE
spam: /browse filled with https-www-reddit-com-* "tests"

### ISSUE THREAD

**Issue by iskitz** [jsperf/jsperf.com#56]
Noticed today, 2016.12.06, that most tests listed at **http://jsperf.com/browse** seem to be spam. They're all named some variant of 
**https-www-reddit-com-** and have this code:

```html
https://www.reddit.com/3vpna9
<script>
  Benchmark.prototype.setup = function() {
    https://www.reddit.com/3vpna9
  };

  Benchmark.prototype.teardown = function() {
    https://www.reddit.com/3vpna9
  };
</script>
```

**Comment by mathiasbynens** [comment]
I’ve removed most of those in the database dump we’ll use for v2.
