### ISSUE TITLE
RSS removed/disabled?  

### ISSUE THREAD

**Issue by zanetu** [jsperf/jsperf.com#60]
I can no longer subscribe to a test on jsperf.com. Will the RSS feature ever come back?

**Comment by maxbeatty** [comment]
To be clear, the currently live jsperf.com is still the PHP version and not this JS-based repository.

[Still waiting](https://github.com/jsperf/jsperf.com/blob/master/server/web/test/index.js#L90) for #14 to be added. Some [other atom feeds](https://github.com/jsperf/jsperf.com/blob/master/server/web/search/index.js#L36-L40) have been moved over. Would really appreciate your help adding test feeds!

Closing as a duplicate of #14
