### ISSUE TITLE
Automate building “wrapped” Benchmark.js

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#64]
On jsPerf we have to use a special custom build of [Benchmark.js](https://github.com/bestiejs/benchmark.js) to avoid creating more global variables than necessary (since it may interfere with people’s tests otherwise).

Historically we’ve used a very old/hacky/ugly build script for that: https://github.com/mathiasbynens/jsperf.com/blob/master/_tmp/build.php

The plan is to create a new standalone script:

* in its own repository: **https://github.com/jsperf/build-benchmark.js-wrapper** (this logic doesn’t belong in the main repository with jsperf.com server code)
* with proper tests to avoid issues like #44, #45, #53 

cc @jdalton

**Comment by jdalton** [comment]
:clap:

**Comment by syedirfan7** [comment]
@mathiasbynens  
i am new to this ... 
is there a live way where i can avoid this error ?

> 

**Uncaught TypeError: Cannot read property 'name' of undefined.**

**message: Uncaught TypeError: Cannot read property 'name' of undefined
fileName: http://jsperf.com/benchmark-47.js
lineNumber: 21**

**Comment by mathiasbynens** [comment]
Okay, the build is ready. What’s left now is to fetch https://jsperf.github.io/build-benchmark.js-wrapper/all.js and save it as [`public/_js/benchmark.js`](https://github.com/jsperf/jsperf.com/blob/master/public/_js/benchmark.js), preferably automatically on each build. I’d prefer not to have this file as part of the repository. @maxbeatty @asilluron what would be the best way to do this?

**Comment by maxbeatty** [comment]
You could publish to npm as a [scoped package](https://docs.npmjs.com/misc/scope) like `@jsperf/build-benchmark.js-wrapper`, add as dependency in `package.json`, and then create [a special route like `robots.txt`](https://github.com/jsperf/jsperf.com/blob/master/server/web/public.js#L15-L21)

```js
  server.route({
    method: 'GET',
    path: '/public/_js/benchmark.js',
    handler: {
      file: require('build-benchmark.js-wrapper')
    }
  });
```

**Comment by mathiasbynens** [comment]
It would have to be something like `require.resolve('@mathias/benchmark.js-wrapper-jsperf')` instead of `require` since the build only works in browser environments.
