### ISSUE TITLE
ES6 Destructuring ?

### ISSUE THREAD

**Issue by pbakondy** [jsperf/jsperf.com#66]
Test case: http://jsperf.com/compare-variable-swapping

FF44 supports ES6 destructuring. I see the following error in the page:

```
TypeError: P(...)[0] is undefined.

    message: TypeError: P(...)[0] is undefined
    fileName: http://jsperf.com/benchmark-47.js
    lineNumber: 21
```

I can not decide if the first case is so slow or the measured Ops/sec is invalid.

**Comment by jdalton** [comment]
This looks like more a [benchmark.js](https://github.com/bestiejs/benchmark.js/) issue.
