### ISSUE TITLE
Unable to benchmark a simple loop with Chrome.

### ISSUE THREAD

**Issue by florentbr** [jsperf/jsperf.com#69]
I tried to benchmark a simple loop with Chrome, but the resuls are erratic and there's an uncaught error.

**Environement :**
Chrome 47.0.2526.111 32-bit on Windows NT 6.3 64-bit

**Test 1:**

    var v = 0;
    for (var i = 0; i < 10000; i++){
      v++;
    }

Result: 33,768 ops/sec
  
**Test 2:**

    var v = 0;
    for (var i = 0; i < 10000; i++){
      v++;
    }

Result: 18,743 ops/sec

**Expected:**
The results should be almost identical, but there's a 44% difference.
There is also an uncaught error displayed :

```
  Uncaught TypeError: Cannot read property 'name' of undefined.
  message: Uncaught TypeError: Cannot read property 'name' of undefined
  fileName: http://jsperf.com/benchmark-47.js
  lineNumber: 21
```
Moreover for the first run the graph displays 28,858 ops/sec and 18,661 ops/sec where it sould be 33,768 Ops/sec and 18,743 ops/sec

**Capture:**

![issue-jsperf](https://cloud.githubusercontent.com/assets/918557/13427452/66465ac8-dfb4-11e5-9eb3-016bed245819.png)

**Comment by maxbeatty** [comment]
Sounds like this should be grouped with the rest (`benchmark-47.jsL21`) in #64

**Comment by mathiasbynens** [comment]
Closing in favor of #64.
