### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#7]
look for a specific test case

https://github.com/maxbeatty/jsperf.com/blob/breakdown/_tpl/search.tpl

**Comment by mathiasbynens** [comment]
Assigned to @MadaraUchiha.

**Comment by maxbeatty** [comment]
Added back in https://github.com/jsperf/jsperf.com/commit/0715e7f5e7814d4b3db93eedcfded187f7c40ae7
