### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by Mottie** [jsperf/jsperf.com#70]
I was trying to run this test: http://jsperf.com/jquery-contains-vs-xpath

and I keep getting a javascript error:

> Uncaught TypeError: Cannot read property 'name' of undefined.

> message: Uncaught TypeError: Cannot read property 'name' of undefined
fileName: http://jsperf.com/benchmark-47.js
lineNumber: 21

**Comment by maxbeatty** [comment]
Closing in favor of #64
