### ISSUE TITLE
Edge detected as Chrome

### ISSUE THREAD

**Issue by dstorey** [jsperf/jsperf.com#71]
Table header says Testing in Chrome, rather than MS Edge

**Comment by dstorey** [comment]
Needs to update to latest version of https://github.com/bestiejs/platform.js/edit/master/platform.js

**Comment by dstorey** [comment]
Paging @jdalton. Uses an ancient version of your platform.js and benchmark.js

**Comment by jdalton** [comment]
Thanks @dstorey!

This should be fixed when the rewrite is finished (fixed in master).

**Comment by dstorey** [comment]
@jdalton thanks. We have an open bug 5946938 in VSO. Do you know when master will go live?

**Comment by jdalton** [comment]
@dstorey I don't have a good estimate on that.

**Comment by mathiasbynens** [comment]
@dstorey You can track the progress in these tickets: #64 and https://github.com/jsperf/build-benchmark.js-wrapper/issues/1.
