### ISSUE TITLE
Gives different results then latest Benchmark.js on a separate site or node.js

### ISSUE THREAD

**Issue by galambalazs** [jsperf/jsperf.com#72]
see:

http://jsperf.com/classes-es6-vs-babel  (gives *incorrect* results for the babel test)

vs.

http://jsbin.com/qadijo (gives same results as node.js *correctly*)

Also my comment here: https://bugs.chromium.org/p/v8/issues/detail?id=4106#c8

**Comment by jdalton** [comment]
The difference is in the jsperf example you're jamming all of the code into the benchmark's setup while in the jsbin/node.js one you're not.

**Comment by galambalazs** [comment]
Right, so it's some kind of optimization of v8 (e.g. there's no 10x difference in Safari)

Declaration should always go into a script tag of the "Preparation code HTML" section?
(and only reseting values in setup?)

**Comment by jdalton** [comment]
The a benchmark looks like this per sample:
```
<setup>
<start clock>
while (<loop count>) {
  < benchmark fn>
}
<end clock>
<teardown>
```

The `setup` is right before the clocked loop so sometimes things in the setup (if doing too much) can effect the loop.

**Comment by galambalazs** [comment]
Interesting. Historically I put almost everything in the Preparation HTML (just by habit), not sure why I defined the classes in Setup in this case (probably just a fast copy&paste)

But one thing it shows is that *Preparation code HTML* could use an additional line:

> Also do any *expensive* declarations and initializations here instead of the Setup section below! 

Cause the current one doesn't seem instructive enough:

> (useful when testing DOM operations or including libraries)
