### ISSUE TITLE
Script Error in benchmark-47.js

### ISSUE THREAD

**Issue by rodneyrehm** [jsperf/jsperf.com#73]
I just added a new test and ran it in a couple of browsers… Chrome says

```
Uncaught TypeError: Cannot read property 'name' of undefined.

message: Uncaught TypeError: Cannot read property 'name' of undefined
fileName: http://jsperf.com/benchmark-47.js
lineNumber: 21
```

<img width="988" alt="screen shot 2016-03-28 at 18 59 40" src="https://cloud.githubusercontent.com/assets/186837/14083785/bf4735a2-f517-11e5-945a-37f9db845e51.png">
<img width="975" alt="screen shot 2016-03-28 at 19 01 06" src="https://cloud.githubusercontent.com/assets/186837/14083787/bf493bf4-f517-11e5-82ad-2b9fe340b24f.png">
<img width="1006" alt="screen shot 2016-03-28 at 18 58 23" src="https://cloud.githubusercontent.com/assets/186837/14083786/bf476e3c-f517-11e5-80ea-eb0fa59881ae.png">

**Comment by maxbeatty** [comment]
Closing in favor of #64
