### ISSUE TITLE
I keep getting "spam detected" when trying to edit a test.

### ISSUE THREAD

**Issue by rconnamacher** [jsperf/jsperf.com#74]
Even when jumping through the CAPTCHA hoops, clearing cookies, waiting those five seconds while that  initial DoS script runs, and trying switching from Safari to Chrome, and waiting a few hours to try again, editing a test I created keeps getting that "spam detected" error page. JSPerf appears to be effectively unusable by me for now.

Frustraingly, editing tests is a fairly slow process with multiple buttons to click and fields to copy text into, and this forces me to start over from scratch every time I want to try again.

How can I debug this?

**Comment by Epochi** [comment]
I can't create new edits either,when I try to publish, I just get reset into edit page, have tried several times in past few hours.

**Comment by lainverse** [comment]
Same here. I made a couple of mistakes in my code when published it and now I can't even fix them.

BTW, lack of a button to test your code before publishing it is the reason here.

**Comment by madskonradsen** [comment]
This applies to the old version of jsperf, which are now offline... i guess it could be closed?
