### ISSUE TITLE
Error message during running test

### ISSUE THREAD

**Issue by NoNameProvided** [jsperf/jsperf.com#75]
It happened multiple times. Running a test will cause this error: 

> Uncaught TypeError: Cannot read property 'name' of undefined.
> - Uncaught TypeError: Cannot read property 'name' of undefined
> - fileName: http://jsperf.com/benchmark-47.js
> - lineNumber: 21

See [this test](http://jsperf.com/replace-first-charachter-of-string-if-it-is-x) for example.

I am not sure maybe I do something wrong or it's a bug in the benchmark.js, but I guess its a bug because I don't have any variable named `name`.

**Comment by maxbeatty** [comment]
Closing in favor of #64
