### ISSUE TITLE
Can't edit a test case

### ISSUE THREAD

**Issue by leonardobazico** [jsperf/jsperf.com#76]
I'm trying to edit a test case with bug, but the test case doesn't update.

[Test case 1](https://jsperf.com/delete-vs-unset-quictest-2)
[Test case 2](https://jsperf.com/angular-foreach-vs-lodash-foreach-with-context)

**Comment by adunkman** [comment]
Experiencing the same issue with https://jsperf.com/data-island-test — it seems that the POST to update the jsperf is returning a 403.

**Comment by nfantone** [comment]
Same issue here on MacOSX and Chrome 49.0.2623.110.

**Comment by madskonradsen** [comment]
This applies to the old version of jsperf, which are now offline... i guess it could be closed?
