### ISSUE TITLE
benchmark.js is broken.

### ISSUE THREAD

**Issue by VenomVendor** [jsperf/jsperf.com#77]
https://jsperf.com/getelementsbyclassname-vs-queryselectorall/25

    Uncaught TypeError: Cannot read property 'name' of undefined.
         · message: Uncaught TypeError: Cannot read property 'name' of undefined
         · fileName: https://jsperf.com/benchmark-47.js
         · lineNumber: 21

https://jsperf.com/www-reddit-com-4e2nyp

    Uncaught SyntaxError: Unexpected token ILLEGAL.
         · message: Uncaught SyntaxError: Unexpected token ILLEGAL
         · fileName:
         · lineNumber: 1

    Uncaught TypeError: Cannot read property 'call' of undefined.
         · message: Uncaught TypeError: Cannot read property 'call' of undefined
         · fileName: https://jsperf.com/benchmark-47.js
         · lineNumber: 14

<img width="600" alt="Benchmark.js broken." src="https://cloud.githubusercontent.com/assets/1086927/14406050/7881712a-febb-11e5-9568-b43f0e608837.png">

**Comment by mathiasbynens** [comment]
#64
