### ISSUE TITLE
README: update setup instructions?

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#84]
Now that #58 is merged, should the setup instructions be updated?

Does [Docker Toolbox](https://www.docker.com/products/docker-toolbox) simplify https://github.com/jsperf/jsperf.com#docker?

**Comment by mathiasbynens** [comment]
Specifically, following the current instructions causes `docker-compose run web node /code/setup/tables` to fail:

```sh
$ docker-compose run web node /code/setup/tables
creating tables [ 'comments', 'pages', 'tests' ]
reading file /code/setup/sql/create_comments.sql
reading file /code/setup/sql/create_pages.sql
reading file /code/setup/sql/create_tests.sql
{ [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'jsperf'@'172.17.0.8' (using password: NO)]
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  fatal: true }
{ [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'jsperf'@'172.17.0.8' (using password: NO)]
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  fatal: true }
{ [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'jsperf'@'172.17.0.8' (using password: NO)]
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  fatal: true }
```

Prefixing the command with `MYSQL_PASSWORD=xxxxxx ` doesn’t make a difference.

The README also mentions `MYSQL_PASS` instead of `MYSQL_PASSWORD`.

**Comment by mathiasbynens** [comment]
@maxbeatty @asilluron Any ideas as to what I’m doing wrong here?

**Comment by asilluron** [comment]
Good catch. Updating the readme instructions. 

I think the fix is to run ``` docker-compose up -d ``` first then ``` docker-compose run web node /code/setup/tables ``` 

Docker-compose automatically exports the env vars needed by the table setup script.

**Comment by mathiasbynens** [comment]
Are you on IRC right now?

**Comment by asilluron** [comment]
I am now.
