### ISSUE TITLE
GitHub OAuth link seems broken

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#87]
On the live version, it looks like `/auth/github` redirects to something like:

```
https://github.com/login/oauth/authorize?client_id="c5c81129b9a53e752727"&response_type=code&redirect_uri="http"%3A%2F%2F"jsperf.com"%2Fauth%2Fgithub&state=xxxxx&scope=user%3Aemail
```

Note that there are excessive URL-encoded quotes around the `client_id` and `redirect_uri` values causing a 404.

**Comment by madskonradsen** [comment]
That sounds like they are being set as:
`"c5c81129b9a53e752727"`
instead of
`c5c81129b9a53e752727`
in the .env file

**Comment by mathiasbynens** [comment]
This seems to have been fixed already in a recent deploy.
