### ISSUE TITLE
home: `[object Object]` is shown instead of the entered slug

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#88]
When adding a new test case and making an error (e.g. by leaving a required field such as the test entries empty), the page is loaded with the previous input pre-filled. However, the slug is then displayed as `[object Object]`:

![](https://cloud.githubusercontent.com/assets/81942/14528383/64a9ca66-024f-11e6-8145-4706112151b9.png)

**Comment by mathiasbynens** [comment]
The same goes for the name input field:

```
      <label for="author">Name </label><input type="text" name="author" id="author" value=by [object Object] >
```

…which renders as just “by”.

**Comment by mathiasbynens** [comment]
Same goes for `/popular`:

```html
<h2 id="all-time">All time</h2>

<ul>
    <li>
      <a href="/empty-vs-html2">.empty() vs. html("")</a>  by by [object Object]  
      (last updated <time datetime="2012-07-11T16:25:50.000Z">on 7/11/2012</time>)
    <li>
[…]
```

**Comment by steponas** [comment]
I've send a pull request for the slug issue.

The Author issue is a bigger one. In short, there is a `author` handlebars helper which takes priority against local variables, the "author" one in this case.

We could go ahead and do it like it's explained in https://github.com/wycats/handlebars.js/issues/209, e.g.

```
<input type="text" name="author" id="author" value="{{this.author}}">
```

but in general I think it's bad practice and leads to confusion.

My suggestion: rename the helper to `formatAuthor`. And use it as such where necessary. From what I see, it should be used only in three places, all being in `server/web/test/index.hbs` - as those are the only references which pass the required parameters to the helper. So I am assuming all other `author`s are just plain-text.

**Comment by steponas** [comment]
Ok, this should be fixed when you accept both PRs.
