### ISSUE TITLE
Add ability to publish private test

### ISSUE THREAD

**Issue by maxbeatty** [jsperf/jsperf.com#9]
https://github.com/maxbeatty/jsperf.com/blob/breakdown/_tpl/publish.tpl

**Comment by asilluron** [comment]
Closed by #113

**Comment by maxbeatty** [comment]
I saw you can toggle private via edit but we're still missing the `/publish` endpoint [here](https://github.com/jsperf/jsperf.com/blob/47eb33d028da534cab541873549a6fe7767867ae/server/web/test/index.hbs#L20). Do we still want to implement that or just remove the link?

**Comment by asilluron** [comment]
😯

I think it's easy enough to implement.
